In [171]:
import pandas as pd
from vertexai.generative_models import (
    FunctionDeclaration,
    GenerationConfig,
    GenerativeModel,
    Tool,
    HarmCategory,
    HarmBlockThreshold
)
import json
import re

In [142]:
import import_ipynb
from get_zip_codes import get_zip_codes

Orders

In [143]:
orders = pd.read_excel('data/Shipped Order Data by Order and line level details for POC.xlsx')

In [144]:
orders

,ORDER_NO,ORDER_SUFFIX,ORDER_LINE_NO,ORDER_ENTERED_DATE,INVOICED_DATE,TRANS_TYPE,CUSTOMER_NO,SHIP_TO_NO,addr_1,addr_2,city,state,zipcd,JOB_TYPE,JOB_TYPE_DESCRIPTION,JOB_SUBTYPE,JOB_SUBTYPE_DESCRIPTION,WAREHOUSE,PRODUCT_CODE,descrip_1,PRODUCT_CAT_DESC,PRODUCT_PRIMARY_CAT_DESC,REPORT_CATEGORY,STOCK_QTY_SHIPPED,STOCK_UOM
0,10000434,0,1,2024-02-01,2024-02-01,so,93290,MISC,1528 W REMINGTON LN,NaN,ROUND LAKE,IL,60073-2390,ZZ,Not Available,NaN,NaN,47,D58F12-CT,"5/8"" 4X12' FC TYPE X","Drywall (5/8"" Standard White Board)",DRYWALL,Core,10.0,SHT
1,10000434,0,1,2024-02-01,2024-02-01,so,93290,MISC,1528 W REMINGTON LN,NaN,ROUND LAKE,IL,60073-2390,ZZ,Not Available,NaN,NaN,47,D58F12-CT,"5/8"" 4X12' FC TYPE X","Drywall (5/8"" Standard White Board)",DRYWALL,Core,10.0,SHT
2,10000434,0,1,2024-02-01,2024-02-01,so,93290,MISC,1528 W REMINGTON LN,NaN,ROUND LAKE,IL,60073-2390,ZZ,Not Available,NaN,NaN,47,D58F12-CT,"5/8"" 4X12' FC TYPE X","Drywall (5/8"" Standard White Board)",DRYWALL,Core,10.0,SHT
3,10000434,0,1,2024-02-01,2024-02-01,so,93290,MISC,1528 W REMINGTON LN,NaN,ROUND LAKE,IL,60073-2390,ZZ,Not Available,NaN,NaN,47,D58F12-CT,"5/8"" 4X12' FC TYPE X","Drywall (5/8"" Standard White Board)",DRYWALL,Core,10.0,SHT
4,10000434,0,1,2024-02-01,2024-02-01,so,93290,MISC,1528 W REMINGTON LN,NaN,ROUND LAKE,IL,60073-2390,ZZ,Not Available,NaN,NaN,47,D58F12-CT,"5/8"" 4X12' FC TYPE X","Drywall (5/8"" Standard White Board)",DRYWALL,Core,10.0,SHT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564075,949003342,0,12,2024-09-30,2024-10-07,so,306650,55EMONRO,55 E. MONROE ST.,JERRY (773)505-7216,CHICAGO,IL,60603-5713,CN,Commerical New,O,Office,49,FRPLY34CDX,"3/4"" 4X8 F/R TREATED CDX",Lumber - Ply. Fire Treat,LUMBER,Complementary and Other,20.0,SHT
564076,949003342,0,12,2024-09-30,2024-10-07,so,306650,55EMONRO,55 E. MONROE ST.,JERRY (773)505-7216,CHICAGO,IL,60603-5713,CN,Commerical New,O,Office,49,FRPLY34CDX,"3/4"" 4X8 F/R TREATED CDX",Lumber - Ply. Fire Treat,LUMBER,Complementary and Other,20.0,SHT
564077,949003342,0,12,2024-09-30,2024-10-07,so,306650,55EMONRO,55 E. MONROE ST.,JERRY (773)505-7216,CHICAGO,IL,60603-5713,CN,Commerical New,O,Office,49,FRPLY34CDX,"3/4"" 4X8 F/R TREATED CDX",Lumber - Ply. Fire Treat,LUMBER,Complementary and Other,20.0,SHT
564078,949003342,0,13,2024-09-30,2024-10-07,so,306650,55EMONRO,55 E. MONROE ST.,JERRY (773)505-7216,CHICAGO,IL,60603-5713,CN,Commerical New,O,Office,49,CGAKAM10B,ARM KNURLED ANGLE,Acoustical - Drywall,CEILINGS,Core,100.0,PC
564079,949003342,0,13,2024-09-30,2024-10-07,so,306650,55EMONRO,55 E. MONROE ST.,JERRY (773)505-7216,CHICAGO,IL,60603-5713,CN,Commerical New,O,Office,49,CGAKAM10B,ARM KNURLED ANGLE,Acoustical - Drywall,CEILINGS,Core,100.0,PC

Boolean Filters

In [145]:
filter_df = pd.read_excel('data/Extracted Data.xlsx')
filter_df

,Name,Assigned User,FilterData
0,Gordon and Rockfon Specs IDAHO Job leads,"Jeannette Holvino, Tim Skaggs",(Gordon Industries NEAR Products) OR (Gordon I...
1,*All Products,Leigh Ann Williams,(armstrong NEAR ceiling*) OR (certainteed NEAR...
2,*All Products - Ben,Ben McNeal,"""clark dietrich"" OR ""clarkdietrich"" OR (armstr..."
3,*All Products Bidding,Leigh Ann Williams,(armstrong NEAR ceiling*) OR (certainteed NEAR...
4,*All Products Planning,Leigh Ann Williams,(armstrong NEAR ceiling*) OR (certainteed NEAR...
...,...,...,...
195,All Results_158955,Ryan Hughes,No Filter is available
196,All Results_158998,Chris Bartlett,No Filter is available
197,All Results_159212,Mathew Bryan,No Filter is available
198,All Results_159723,Stu Marshall,No Filter is available
199,All Results_159812,,No Filter is available

In [146]:
known_filters = filter_df['FilterData'].unique().tolist()
known_filters.remove('No Filter is available')
len(known_filters)

13

In [147]:
known_filters

['(Gordon Industries NEAR Products) OR (Gordon Industries NEAR Manufacturer) OR ("Mullion" NEAR ceiling) OR ("Mullion" NEAR ceilings) OR (Rockfon NEAR ceilings) OR (Rockfon NEAR ceiling)',
 '(armstrong NEAR ceiling*) OR (certainteed NEAR drywall*) OR (certainteed NEAR gypsum*) OR (usg NEAR drywall*) OR (usg NEAR gypsum*) OR ("united states gypsum" NEAR drywall*) OR ("united states gypsum" NEAR gypsum*) OR "national gypsum" OR (eifs NEAR sto) OR eifs OR "g&s" OR "g & s" OR tectum OR "golterman & sabo" OR (turf NEAR "wall panel") OR (turf NEAR "wall panels") OR frasch',
 '"clark dietrich" OR "clarkdietrich" OR (armstrong NEAR ceiling*)',
 '(armstrong NEAR ceiling*) OR (usg NEAR ceiling*) OR ("united states gypsum" NEAR ceiling*) OR (rockfon NEAR ceiling*) OR ("certainteed" NEAR ceiling*)',
 'hammond',
 '(USG NEAR ceiling) OR (USG NEAR ceilings)',
 '(armstrong NEAR ceiling) OR (usg NEAR ceiling) OR ("united states gypsum" NEAR ceiling) OR (armstrong NEAR ceilings) OR (usg NEAR ceilings) OR ("united states gypsum" NEAR ceilings)',
 '(eifs NEAR adex) OR (eifs NEAR dryvit) OR (eifs NEAR sto) OR (eifs NEAR parex) OR (stucco NEAR adex) OR (stucco NEAR dryvit) OR (stucco NEAR sto) OR (stucco NEAR parex)',
 '(usg NEAR drywall) OR (usg NEAR gypsum) OR "united states gypsum" OR (certainteed NEAR gypsum) OR (certainteed NEAR drywall) OR "national gypsum" OR ("georgia pacific" NEAR gypsum) OR (pabco NEAR gypsum) OR ("georgia pacific" NEAR drywall) OR (pabco NEAR drywall)',
 '"acoustical ceilings*"',
 '(armstrong NEAR ceiling) OR (armstrong NEAR ceilings) OR (certainteed NEAR ceiling) OR (certainteed NEAR ceilings)',
 '(sto NEAR eifs) OR (sto NEAR stucco) OR (armstrong NEAR ceiling*) OR mapei OR schluter',
 '(eifs NEAR adex) OR (eifs NEAR dryvit) OR (eifs NEAR sto) OR (eifs NEAR parex) OR (stucco NEAR adex) OR (stucco NEAR dryvit) OR (stucco NEAR sto) OR (stucco NEAR parex) OR Specified technologies OR (sti NEAR firestop*) OR (sti NEAR fire stop*) OR metacaulk OR (rectorseal NEAR firestop*) OR (rectorseal NEAR fire stop*) OR (hilti NEAR firestop*) OR (hilti NEAR fire stop*) OR ("fiberglass reinforced plastic") OR ("FRP panel") OR (Gordon Industries NEAR Products) OR (Gordon Industries NEAR Manufacturer) OR ("Mullion" NEAR ceiling) OR ("Mullion" NEAR ceilings) OR (Rockfon NEAR ceilings) OR (Rockfon NEAR ceiling) OR (armstrong NEAR ceiling) OR (armstrong NEAR ceilings) OR (certainteed NEAR ceiling) OR (certainteed NEAR ceilings) OR (usg NEAR gypsum) OR (usg NEAR drywall) OR (certainteed NEAR gypsum) OR (certainteed NEAR drywall) OR "united states gypsum" OR "american gypsum" OR ("georgia pacific" NEAR gypsum) OR ("georgia pacific" NEAR drywall) OR "national gypsum"']

Boolean text files

In [175]:
boolean_df = pd.read_csv('data/boolean_filters.csv')
boolean_df

,Filter,Query
0,Drywall Sales,(usg NEAR drywall) OR (usg NEAR gypsum) OR ('u...
1,Certainteed Drywall Sales,(certainteed NEAR drywall) OR (certainteed NEA...
2,Georgia Pacific Drywall Sales,('georgia pacific' NEAR drywall) OR ('georgia ...
3,Pabco Drywall Sales,(pabco NEAR drywall) OR (pabco NEAR gypsum)
4,Ceiling Sales,(armstrong NEAR ceiling) OR (armstrong NEAR ce...
5,EIFS & Stucco Sales,(sto NEAR eifs) OR (sto NEAR stucco) OR (stoti...
6,Cultured Stone Sales,(cor NEAR stone) OR (cultured NEAR stone) OR (...
7,Steel Sales,(steel) OR (stud) OR (track) OR (angle) OR ('f...
8,Insulation Sales,(insulation) OR ('mineral wool') OR (fiberglas...
9,Fastener Sales,(fastener) OR (screw) OR (nail) OR (staple) OR...
10,Fasteners - Ramset,(RAMSET) OR (RAM)
11,Fasteners - Meyer,(MEYER) OR (MEY)
12,Fasteners - Spotnails,(SPOTNAILS) OR (SPO)
13,Fasteners - Trimtex,(TRIMTEX) OR (TTX) OR (TTB)
14,Tool Sales,(tool) OR (knife) OR (trowel) OR (hawk) OR ('m...
15,Tools - DeWalt,(DEWALT) OR (DWD) OR (ROT) OR (DW)
16,FRP Sales,(FRP) OR (Glasbord) OR (Crane) OR (Titebond) O...
17,Access Door Sales,(access door) OR (access doors) OR (cendrex) O...
18,Other Sales,(poly) OR (masking) OR ('red rosin') OR ('RED ...
19,Fry Reglet Sales,(FRY NEAR REGLET) OR (FRYDRM) OR ('PROTRUDING'...
20,3M Sales,(3M) OR (3M8511) OR (3M60921) OR (3M6300) OR (...
21,Adapa Sales,('ADAPA') OR ('ADAPA CART SLIDE PLATE') OR ('A...
22,Nichiha Sales,(NICHIHA) OR ('NICHIHA VINTAGEWOOD') OR ('VINT...
23,Panelmax Sales,(PANELMAX) OR (PMX)

In [150]:
df_ordered

,Filter,Query
4,Ceiling Sales - Armstrong,(armstrong NEAR ceiling) OR (armstrong NEAR ce...
1,Certainteed Drywall Sales,(certainteed NEAR drywall) OR (certainteed NEA...
0,Drywall Sales,(usg NEAR drywall) OR (usg NEAR gypsum) OR ('u...
2,Georgia Pacific Drywall Sales,('georgia pacific' NEAR drywall) OR ('georgia ...
3,Pabco Drywall Sales,(pabco NEAR drywall) OR (pabco NEAR gypsum)

In [151]:
product_categories = df_ordered.Filter.unique().tolist()
product_categories

['Ceiling Sales - Armstrong',
 'Certainteed Drywall Sales',
 'Drywall Sales',
 'Georgia Pacific Drywall Sales',
 'Pabco Drywall Sales']

Construct Connect data

In [152]:
construct_connect_data = pd.read_pickle('data/construct_connect_data.pkl')

In [ ]:
cc_data_Subset = construct_connect_data[:5]
cc_projects_json_records = cc_data_Subset.to_json(orient='records')

In [177]:
cc_projects_json_records

'[{"ProjectID":1006882884,"DataSourceID":"US","Title":"Bojangles \\/ Chicago","Stage":"Pre-Design","URL":"http:\\/\\/insight.cmdgroup.com\\/SingleSignOn\\/ProjectDetails\\/1006882884\\/1\\/","UpdateDate":"2024-02-16","IsProspective":false,"UpdateText":"Project Details or Scope was Added\\/Updated","Valuation_Value":"900000.00","Valuation_Currency":"USD","Valuation_ValueType":"Staff Estimate Value","Parameters_Parameter_Ownership":"Private","Parameters_Parameter_WorkType":"New","Parameters_Parameter_CommenceDate":"2025-09-05","Parameters_Parameter_FloorArea":null,"Parameters_Parameter_Structures":1.0,"Parameters_Parameter_Units":null,"Parameters_Parameter_BidDate":null,"Parameters_Parameter_FloorAreaUnitofMeasure":null,"Parameters_Parameter_IsSingleTrade":false,"DocumentAvailability_Plans":false,"DocumentAvailability_Specs":false,"DocumentAvailability_Addenda":false,"ParentCategories_PrimaryCategoryName":"Restaurants","ParentCategories_ParentCategory":[{"_Name":null,"ns0:SubCategories":{"ns0:SubCategory":["Restaurants"]}}],"Addresses_Address":[{"_ProjectAddressType":null,"ns0:AddressLine1":"To Be Determined","ns0:AddressLine2":null,"ns0:City":"Chicago","ns0:CountryRegion":"UNITED STATES","ns0:County":"Cook","ns0:Latitude":41.875734,"ns0:Longitude":-87.625562,"ns0:StateProvince":"IL","ns0:ZipPostalCode":"60604"}],"Contracts_Contract":[],"ProjectEvents_ProjectEvent":[{"ns0:Event":"Start Date","ns0:EventDate":"2025-09-05","ns0:EventDetails":"Actual Start Date","ns0:EventTime":null}],"Companies":[{"ns0:Company":[{"_BiddingRole":null,"_CompanyID":null,"_DataSourceID":null,"_LastUpdate":null,"_Name":null,"_Role":null,"_URL":null,"ns0:Addresses":{"ns0:Address":[{"_AddressType":null,"ns0:AddressLine1":"9432 Southern Pine Blvd.","ns0:AddressLine2":null,"ns0:City":"Charlotte","ns0:CountryRegion":"UNITED STATES","ns0:County":"Mecklenburg","ns0:StateProvince":"NC","ns0:ZipPostalCode":"28273"}]},"ns0:BidderRoles":null,"ns0:ClassificationTypes":{"ns0:ClassificationType":[{"_Rank":null,"_Type":null}]},"ns0:Contacts":{"ns0:Contact":[{"_ContactID":null,"_Name":null,"ns0:Email":"cclark@bojangles.com","ns0:LinkedInURL":"http:\\/\\/www.linkedin.com\\/pub\\/claude-clark\\/18\\/9b2\\/45","ns0:PhoneNumber":"7049408669"},{"_ContactID":null,"_Name":null,"ns0:Email":null,"ns0:LinkedInURL":null,"ns0:PhoneNumber":null},{"_ContactID":null,"_Name":null,"ns0:Email":null,"ns0:LinkedInURL":null,"ns0:PhoneNumber":null},{"_ContactID":null,"_Name":null,"ns0:Email":null,"ns0:LinkedInURL":null,"ns0:PhoneNumber":null},{"_ContactID":null,"_Name":null,"ns0:Email":"tommy.rogers@bojangles.com","ns0:LinkedInURL":null,"ns0:PhoneNumber":"4347704923"},{"_ContactID":null,"_Name":null,"ns0:Email":"beasterling@bojangles.com","ns0:LinkedInURL":null,"ns0:PhoneNumber":"8003669921"},{"_ContactID":null,"_Name":null,"ns0:Email":"athomas@bojangles.com","ns0:LinkedInURL":null,"ns0:PhoneNumber":"7045192104"},{"_ContactID":null,"_Name":null,"ns0:Email":"gemory@bojangles.com","ns0:LinkedInURL":"https:\\/\\/www.linkedin.com\\/in\\/ginny-emory-54b2077\\/","ns0:PhoneNumber":"7045272675"},{"_ContactID":null,"_Name":null,"ns0:Email":"bchandler@bojangles.com","ns0:LinkedInURL":"https:\\/\\/www.linkedin.com\\/in\\/realestatedevelopment2\\/","ns0:PhoneNumber":"7045272675"},{"_ContactID":null,"_Name":null,"ns0:Email":"hmckone@bojangles.com","ns0:LinkedInURL":"https:\\/\\/www.linkedin.com\\/in\\/hilary-mckone-09463a36\\/","ns0:PhoneNumber":"7045272675"},{"_ContactID":null,"_Name":null,"ns0:Email":"ipipitone@bojangles.com","ns0:LinkedInURL":"https:\\/\\/www.linkedin.com\\/in\\/iggy-pipitone-4a020b9\\/","ns0:PhoneNumber":"6156740529"},{"_ContactID":null,"_Name":null,"ns0:Email":null,"ns0:LinkedInURL":null,"ns0:PhoneNumber":"7063465157"}]},"ns0:Email":null,"ns0:ParticipantRoles":{"ns0:ParticipantRole":{"_ContactId":null,"_ContactName":null,"_RoleClassification":null,"_RoleStatus":null}},"ns0:Phones":{"ns0:Phone":[{"_":null,"_PhoneType":null},{"_":null,"_PhoneType":null}]},"ns0:Website":"https:\\/\\/www.bojangles.com\\/"}]}],"Users":[{"ns0:User":[{"_ProjectFlaggedForExport":null,"_UserFullName":null,"_UserId":null,"_UserName":null,"ns0:Queries":{"ns0:Query":[{"_DocCenterUrl":null,"_QueryId":null,"_QueryName":null}]}}]}],"UpdateSummarizations_UpdateSummary":[{"_Summary":null,"_UpdateSummaryDate":null},{"_Summary":null,"_UpdateSummaryDate":null},{"_Summary":null,"_UpdateSummaryDate":null}],"PlanSpecs":[],"Details_Detail_Scope":["Site work and new construction of a restaurant in Chicago, Illinois. Conceptual plans call for the construction of a restaurant.\\nPlans call for new construction of a Fast-Food Restaurant. As of February 16, 2024, this project is in planning stages. Information regarding the architect, general contractor, and method of selection has not been disclosed. An exact location has not been determined, but is not expected to open until 2026. *Project information, including timeline and contacts, has been obtained through public sources. The content management team continues to pursue additional details; however, the contact(s) listed have yet to disclose or confirm any information. Inquiries should be directed to the contact(s) listed."],"Details_Detail_Notes":["Development include(s):  New Construction, Site Work"],"Details_Detail_Details":[],"Details_Detail":[{"_":null,"_DetailType":null},{"_":null,"_DetailType":null}],"Materials_Material":[],"RSMeansMaterialDivisions_Division_Concrete":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Masonry":[],"RSMeansMaterialDivisions_Division_Metals":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_WoodPlasticsandComposites":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_ThermalandMoistureProtection":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Openings":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Finishes":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Furnishings":[],"RSMeansMaterialDivisions_Division_ConveyingEquipment":[],"RSMeansMaterialDivisions_Division_FireSuppression":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Plumbing":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_HeatingVentilatingandAirConditioningHVAC":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Electrical":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Communications":[],"RSMeansMaterialDivisions_Division_ElectronicSafetyandSecurity":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Earthwork":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Utilities":[],"Notes":null,"ListDate":"2023-08-16","Connections":[],"Parameters_Parameter_CompletionDate":null,"Parameters_Parameter_MandatoryPreBidConferenceDate":null,"RSMeansMaterialDivisions_Division_Specialties":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Equipment":[],"Parameters_Parameter_FloorsAboveGround":null,"RSMeansMaterialDivisions_Division_GeneralRequirements":[],"RSMeansMaterialDivisions_Division_SpecialConstruction":[],"Parameters_Parameter_LEEDCertificationIntent":null,"Parameters_Parameter_ParkingSpaces":null,"Parameters_Parameter_BidTime":null,"Parameters_Parameter_FloorsBelowGround":null,"ProjectParentID":null,"Parameters_Parameter_SiteArea":null,"Parameters_Parameter_SiteAreaUnitofMeasure":null,"Parameters_Parameter_GreenBuildingCertification":null,"Details_Detail_ContractConditions":[],"Details":null,"Details_Detail_Subbids":[],"Details_Detail_Quantity_Unitprices":[],"Parameters_Parameter_SingleTradeClassification":null,"timeCreated":"2024-12-01T21:04:50.699Z","sourceFile":"1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml","Notes_Note":[],"Details_Detail_Status":[]},{"ProjectID":1006877272,"DataSourceID":"US","Title":"21st Street Multi-Residential","Stage":"General Contractor Award","URL":"http:\\/\\/insight.cmdgroup.com\\/SingleSignOn\\/ProjectDetails\\/1006877272\\/1\\/","UpdateDate":"2023-08-23","IsProspective":false,"UpdateText":"4-D Development was added as Design Build Contractor","Valuation_Value":"200000.00","Valuation_Currency":"USD","Valuation_ValueType":"Staff Estimate Value","Parameters_Parameter_Ownership":"Private","Parameters_Parameter_WorkType":"New","Parameters_Parameter_CommenceDate":"2023-08-28","Parameters_Parameter_FloorArea":null,"Parameters_Parameter_Structures":2.0,"Parameters_Parameter_Units":3.0,"Parameters_Parameter_BidDate":null,"Parameters_Parameter_FloorAreaUnitofMeasure":null,"Parameters_Parameter_IsSingleTrade":false,"DocumentAvailability_Plans":false,"DocumentAvailability_Specs":false,"DocumentAvailability_Addenda":false,"ParentCategories_PrimaryCategoryName":"Apartments","ParentCategories_ParentCategory":[{"_Name":null,"ns0:SubCategories":{"ns0:SubCategory":["Apartments"]}}],"Addresses_Address":[{"_ProjectAddressType":null,"ns0:AddressLine1":"1952 W 21st St","ns0:AddressLine2":null,"ns0:City":"Chicago","ns0:CountryRegion":"UNITED STATES","ns0:County":"Cook","ns0:Latitude":41.849103,"ns0:Longitude":-87.667335,"ns0:StateProvince":"IL","ns0:ZipPostalCode":"60608"}],"Contracts_Contract":[],"ProjectEvents_ProjectEvent":[{"ns0:Event":"Start Date","ns0:EventDate":"2023-08-28","ns0:EventDetails":"Actual Start Date","ns0:EventTime":null}],"Companies":[{"ns0:Company":[{"_BiddingRole":null,"_CompanyID":null,"_DataSourceID":null,"_LastUpdate":null,"_Name":null,"_Role":null,"_URL":null,"ns0:Addresses":{"ns0:Address":[{"_AddressType":null,"ns0:AddressLine1":"Henry Drive and 191st Street","ns0:AddressLine2":null,"ns0:City":"Mokena","ns0:CountryRegion":"UNITED STATES","ns0:County":"Will","ns0:StateProvince":"IL","ns0:ZipPostalCode":"60448"}]},"ns0:BidderRoles":null,"ns0:ClassificationTypes":{"ns0:ClassificationType":[{"_Rank":null,"_Type":null}]},"ns0:Contacts":null,"ns0:Email":null,"ns0:ParticipantRoles":{"ns0:ParticipantRole":{"_ContactId":null,"_ContactName":null,"_RoleClassification":null,"_RoleStatus":null}},"ns0:Phones":{"ns0:Phone":[{"_":null,"_PhoneType":null},{"_":null,"_PhoneType":null}]},"ns0:Website":null}]}],"Users":[{"ns0:User":[{"_ProjectFlaggedForExport":null,"_UserFullName":null,"_UserId":null,"_UserName":null,"ns0:Queries":{"ns0:Query":[{"_DocCenterUrl":null,"_QueryId":null,"_QueryName":null},{"_DocCenterUrl":null,"_QueryId":null,"_QueryName":null}]}}]}],"UpdateSummarizations_UpdateSummary":[{"_Summary":null,"_UpdateSummaryDate":null},{"_Summary":null,"_UpdateSummaryDate":null}],"PlanSpecs":[],"Details_Detail_Scope":["Demolition, site work and new construction of a multi-residential development in Chicago, Illinois. Completed plans call for the construction of a three-story above grade, three-unit multi-residential development; and for the demolition of a multi-residential development.\\nScope: three-story apartment building with an added basement, set to house three individual dwelling units. The project is expected to replace a former three-story brick building. Permits have been issued and construction is expected to begin in late August 2023. All trades are let."],"Details_Detail_Notes":["Development include(s):  New Construction, Demolition, Site Work"],"Details_Detail_Details":[],"Details_Detail":[{"_":null,"_DetailType":null},{"_":null,"_DetailType":null}],"Materials_Material":[],"RSMeansMaterialDivisions_Division_Concrete":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Masonry":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Metals":[],"RSMeansMaterialDivisions_Division_WoodPlasticsandComposites":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_ThermalandMoistureProtection":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Openings":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null},{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":null,"_TotalCostValue":null}],"RSMeansMaterialDivisions_Division_Finishes":[{"_":null,"_Code":null,"_InstallationCostValue":null,"_MaterialCostValue":nu

LLM model

In [154]:
PROJECT_ID = "proj-sales-recommender-dev"
LOCATION = "us-central1" 

import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

In [155]:
MODEL_ID = "gemini-1.5-flash" 

model = GenerativeModel(
    MODEL_ID,
    safety_settings={
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
        },

)

Justin's prompt

In [156]:

question = f'''

**Objective:** Classify ConstructConnect projects as very high, high, moderate, low, very low and not relevant.

**Product Categories:**

{product_categories}

**Instructions:**

1. **Analyze the provided JSON data** representing ConstructConnect projects to understand relevant fields and data.
2. **Utilize the Boolean filters** corresponding to each product category (provided below) to identify relevant keywords and phrases.
3. **Classify projects:**
    * In stages indicating active procurement (e.g., "Biddate Set", "SUBBIDS: ASAP", "Post Bid", "Low Bids Announced").
    * Containing a substantial number of matching products and phrases across multiple fields, prioritizing specific materials mentioned.
    * Near the specified geographical area.
    * If all else is equal, assign higher priority to higher value projects.
4. **Estimate the relevancy of each project** based on the strength of product matches, project stage, proximity to specified geography, and total dollar amount. 
5. **Respond with a list of project evaluations** in valid JSON as provided in the Example Output below. Classify the projects as very high, high, moderate, low, very low and not relevant.


**JSON Project Data:** 
{cc_projects_json_records}

**Geographical Area:**
Any

**Boolean Filters:**
{f_dict}

**Example Output:**
[
{{"ProjectID": 1006193703, "Relevance Classification": High, "Reasoning": reason for match}},
{{"ProjectID": 1006193700, "Relevance Classification": Low, "Reasoning": reason for match}}, 
{{"ProjectID": 1006193702, "Relevance Classification": Not relevant, "Reasoning": reason for match}}
]

'''

prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1006877272,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the General Contractor Award stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006887109,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Construction Underway stage and is a mixed-use development with 149 units, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006894126,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a mixed-use development with 88 units, indicating potential for drywall use. The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006897214,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the General Contractor Award stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007209685,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a medical office project."
  },
  {
    "ProjectID": 1007202459,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is an addition to an educational facility, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007192557,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a multi-residential development with a community center and a fire/police station."
  },
  {
    "ProjectID": 1007196973,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, and is an auditorium project."
  },
  {
    "ProjectID": 1007209015,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007207656,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1007205490,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1007202966,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007191023,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Schematic Design stage, no mention of drywall or ceilings, but the project is a multi-residential development with a fitness/recreation center, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007182734,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the pre-design stage, the scope mentions \"28,000-square-foot, 48-bed medical facility\", which strongly suggests drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007209735,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a mixed-use development with an educational facility and apartments, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007207472,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is an office development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007198990,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007196854,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1007203333,
    "Relevance Classification": "Very high",
    "Reasoning": "Project is in the Biddate Set stage with a bid date of 2024-07-31, and the scope explicitly mentions \"Concrete foundation, Asphalt, Concrete curbs, Masonry, Roofing, Plumbing, Electrical, HVAC\", indicating a high potential for drywall use. The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007209694,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a medical office project."
  },
  {
    "ProjectID": 1007209689,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a medical office project."
  },
  {
    "ProjectID": 1007183717,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a medical office project."
  },
  {
    "ProjectID": 1007187083,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Design Development stage and is a mixed-use development with 500 units, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007196975,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, and is a retail project."
  },
  {
    "ProjectID": 1007196971,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a community center, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007191661,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Design Development stage, and is a mixed-use development with 5.5 million-square-feet and containing residential units, a hotel, and retail, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007191657,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Design Development stage and is a mixed-use development with 7.2 million-square-feet, containing residential units, a hospital, and retail, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006515488,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the pre-design stage and is a multi-residential development with 359 units, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006514978,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006505800,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is a duplicate project, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006504140,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006501300,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development with offices, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006509084,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, but the project is a multi-residential development with retail, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006509056,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Schematic Design stage, no mention of drywall or ceilings, but the project is a school, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006507328,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006501357,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006497108,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006495850,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006495539,
    "Relevance Classification": "Very high",
    "Reasoning": "Project is in the Construction Underway stage, and the scope explicitly mentions \"Construction of a 4,700-square-foot service station \/ car wash facility\", strongly suggesting drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007078163,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007088810,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007074366,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is a duplicate project, no mention of drywall or ceilings, but the project is a restaurant, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007095379,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a retail project."
  },
  {
    "ProjectID": 1007099481,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a manufacturing project with offices and a warehouse, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007101241,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Schematic Design stage, no mention of drywall or ceilings, but the project is a multi-residential development with a community center and a library, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007106384,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007094751,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is an office project."
  },
  {
    "ProjectID": 1007105988,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Post Bid stage, and the scope explicitly mentions \"structural steel for level 1 and light gauge framed for levels 2-6\", indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007086044,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1007086032,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, and is a restaurant project."
  },
  {
    "ProjectID": 1006470732,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006485955,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006493256,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006493842,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the General Contractor Award stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006491121,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006493226,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the General Contractor Award stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006493244,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006489292,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006485984,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006473511,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006470866,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006470817,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006487910,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Post Bid stage, the scope mentions \"Addition to an existing automotive repair facility\", which may involve drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006484222,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007094329,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a mixed-use development with a restaurant, apartments, and offices, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007085411,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the pre-design stage, no mention of drywall or ceilings, but the project is a multi-residential development with offices, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007085399,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Schematic Design stage and is a mixed-use development with 210 units, indicating a high potential for drywall use.  The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007099533,
    "Relevance Classification": "Not relevant",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, and is a shopping center project."
  },
  {
    "ProjectID": 1007094329,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Construction Documents stage, no mention of drywall or ceilings, but the project is a mixed-use development with a restaurant, apartments, and offices, indicating potential for drywall use."
  },
  {
    "ProjectID": 1007079080,
    "Relevance Classification": "Moderate",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a multi-residential development with 43 units, indicating potential for drywall use. The project is in the specified geographic area."
  },
  {
    "ProjectID": 1007101212,
    "Relevance Classification": "High",
    "Reasoning": "Project is in the Design Development stage, no mention of drywall or ceilings, but the project is a multi-residential development with 29 units, indicating potential for drywall use. The project is in the specified geographic area."
  },
  {
    "ProjectID": 1006470732,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {
    "ProjectID": 1006485955,
    "Relevance Classification": "Very low",
    "Reasoning": "Project is in the Construction Underway stage, no mention of drywall or ceilings, but the project is a multi-residential development, indicating potential for drywall use."
  },
  {

Variation 1

In [157]:
question = f''' You are a system used for classifying ConstructConnect projects based on relevancy. 
Your task is to classify the provided project as high, medium and low relevance based on the probablity of the project to win a bid. 
The projects are classified based on the categories of the products, the project stage, the geographical area, and the total dollar amount.
You are provided with:
1.  a JSON data representing ConstructConnect projects {cc_projects_json_records},
2. a list of product categories{product_categories} of interest, 
3. boolean filters corresponding to each product category {f_dict}.
You need to analyze the JSON data to understand the relevant fields and data, utilize the boolean filters to identify relevant keywords and phrases, and classify the projects based on the provided instructions.
You need to respond with a list of project evaluations in valid JSON format, including the ProjectID, Relevance Classification, and Reasoning for the classification.
The Relevance Classification should be High, Medium, or Low, indicating the probability of the project to win a bid.
The Reasoning should provide a brief explanation of the classification, including the strength of product matches, project stage, proximity to the specified geography, and total dollar amount.'''


prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process. Additionally, the project scope involves 'Site work and new construction of a restaurant' which does not strongly align with the provided product categories.  The project valuation of $900,000 is relatively small."
  },
  {
    "ProjectID": 1006877272,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'General Contractor Award' stage, suggesting that the general contractor has been selected, and subcontractor bidding may be occurring. While the project category 'Apartments' does not directly match the provided product categories, the project scope includes 'Demolition' and 'New Construction', which could involve drywall work. The project valuation of $200,000 is moderate."
  },
  {
    "ProjectID": 1006887109,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. While the project category 'Apartments' could involve drywall, the project scope focuses on 'Site work, paving' and 'New Construction' of a mixed-use development, which is not a strong match for the provided product categories. The project valuation of $41,000,000 is large."
  },
  {
    "ProjectID": 1006894126,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' could involve drywall work, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $86,400,000 is very high, indicating a significant potential for drywall sales."
  },
  {
    "ProjectID": 1006897214,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'General Contractor Award' stage, suggesting that the general contractor has been selected, and subcontractor bidding may be occurring. The project category 'Apartments' could involve drywall work, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $10,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1006877621,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. While the project category 'Apartments' could involve drywall, the project scope focuses on 'Site work' and 'New Construction' of a mixed-use development, which is not a strong match for the provided product categories. The project valuation of $16,000,000 is large."
  },
  {
    "ProjectID": 1006877599,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' could involve drywall work, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $4,400,000 is moderate, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007209685,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Medical Offices' does not strongly align with the provided product categories, and the project valuation of $500,000 is relatively small."
  },
  {
    "ProjectID": 1007202459,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. However, the project category 'College, University' could involve drywall work, and the project scope includes 'Addition' and 'Demolition', further increasing the probability of drywall usage.  The project valuation of $3,200,000 is moderate."
  },
  {
    "ProjectID": 1007192557,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Apartments' could involve drywall work, but the project scope is very broad, and the project valuation of $32,000,000 is large."
  },
  {
    "ProjectID": 1007196973,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Auditoriums' could involve drywall work, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $4,000,000 is moderate."
  },
  {
    "ProjectID": 1007209015,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' could involve drywall work, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $7,800,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007207656,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Restaurants' does not strongly align with the provided product categories, and the project valuation of $500,000 is relatively small."
  },
  {
    "ProjectID": 1007205490,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Restaurants' does not strongly align with the provided product categories, and the project valuation of $1,000,000 is relatively small."
  },
  {
    "ProjectID": 1007202966,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. However, the project category 'Apartments' could involve drywall work, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $638,400 is moderate."
  },
  {
    "ProjectID": 1007191023,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Schematic Design' stage, suggesting that the project is in the early design phases.  The project category 'Apartments' could involve drywall work, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $11,693,200 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007182734,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is early in the planning process.  The project category 'Hospitals, Clinics' strongly aligns with the provided product categories, and the project scope includes 'Addition', 'Demolition', 'Paving', and 'Site Work', further increasing the probability of drywall usage.  The project valuation of $27,120,044 is very high, indicating significant potential for drywall sales."
  },
  {
    "ProjectID": 1007196975,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Retail Stores' could involve drywall work, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $3,000,000 is moderate."
  },
  {
    "ProjectID": 1007209694,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Medical Offices' does not strongly align with the provided product categories, and the project valuation of $500,000 is relatively small."
  },
  {
    "ProjectID": 1007209689,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Medical Offices' does not strongly align with the provided product categories, and the project valuation of $500,000 is relatively small."
  },
  {
    "ProjectID": 1007207472,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Offices' strongly aligns with the provided product categories, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $6,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007207320,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' could involve drywall work, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $1,200,000 is moderate."
  },
  {
    "ProjectID": 1007198990,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $4,536,000 is moderate, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007196854,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process. The project category 'Restaurants' does not strongly align with the provided product categories, and the project valuation of $500,000 is relatively small."
  },
  {
    "ProjectID": 1007191661,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that the project is in the early design phases.  The project category 'Apartments' could involve drywall work, but the project scope is very broad, and the project valuation of $2,500,000,000 is extremely large, making it less likely to be a good fit for the provided product categories."
  },
  {
    "ProjectID": 1007191657,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that the project is in the early design phases.  The project category 'Hospitals, Clinics' strongly aligns with the provided product categories, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $3,000,000,000 is extremely large, making it less likely to be a good fit for the provided product categories."
  },
  {
    "ProjectID": 1007196971,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Clubs, Community Centers' could involve drywall work, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $10,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007078163,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $5,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007088810,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is early in the planning process.  The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage.  The project valuation of $2,776,000 is moderate, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007074366,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is classified as a 'Duplicate Project', indicating that it is not a valid lead.  The project category 'Restaurants' does not strongly align with the provided product categories, and the project valuation of $100,000 is very small."
  },
  {
    "ProjectID": 1007099481,
    "RelevanceClassification": "Medium",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Manufacturing' could involve drywall work, but the project scope is very broad, and the project valuation of $40,000,000 is very large."
  },
  {
    "ProjectID": 1007099533,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Shopping Centers' strongly aligns with the provided product categories, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $5,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007101241,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Schematic Design' stage, suggesting that the project is in the early design phases.  The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $33,000,000 is very high, indicating significant potential for drywall sales."
  },
  {
    "ProjectID": 1007106384,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Construction Documents' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Site work' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $2,000,000 is moderate, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007079080,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, suggesting that detailed plans are being finalized, and subcontractor bidding may be happening soon. The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'Demolition' and 'New Construction', further increasing the probability of drywall usage. The project valuation of $15,000,000 is large, indicating potential for drywall sales."
  },
  {
    "ProjectID": 1007095379,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process. The project category 'Retail Stores' does not strongly align with the provided product categories, and the project valuation of $4,600,000 is moderate."
  },
  {
    "ProjectID": 1007094751,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process. The project category 'Offices' does not strongly align with the provided product categories, and the project valuation of $1,000,000 is relatively small."
  },
  {
    "ProjectID": 1007105988,
    "RelevanceClassification": "High",
    "Reasoning": "The project is in the 'Post Bid' stage, suggesting that the general contractor has been selected, and subcontractor bidding has likely occurred. The project category 'Apartments' strongly aligns with the provided product categories, and the project scope includes 'New Construction', further increasing the probability of drywall usage. The project valuation of $75,000,000 is very high, indicating significant potential for drywall sales."
  },
  {
    "ProjectID": 1006515488,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, indicating that it is very early in the planning process.  The project category 'Apartments' could involve drywall work, but the project scope is very broad, and the project valuation of $140,000,000 is extremely large, making it less likely to be a good fit for the provided product categories."
  },
  {
    "ProjectID": 1006514978,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. While the project category 'Apartments' could involve drywall, the project scope focuses on 'Demolition' and 'New Construction' of a mixed-use development, which is not a strong match for the provided product categories. The project valuation of $800,000 is moderate."
  },
  {
    "ProjectID": 1006505800,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is classified as a 'Duplicate Project', indicating that it is not a valid lead.  The project category 'Apartments' could involve drywall work, but the project scope is very broad, and the project valuation of $13,000,000 is large."
  },
  {
    "ProjectID": 1006504140,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. While the project category 'Apartments' could involve drywall, the project scope focuses on 'Site work' and 'New Construction' of a mixed-use development, which is not a strong match for the provided product categories. The project valuation of $380,000 is moderate."
  },
  {
    "ProjectID": 1006501300,
    "RelevanceClassification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, meaning that subcontractor bidding is unlikely. While the project category 'Apartments' could involve drywall, the project scope focuses on 'Site work' and 'New Construction' of a mixed-use development, which is not a strong match for the provided product categories. The project valuation of $1,290,000 is moderate."
  },
  {
    "ProjectID": 1006497108,
    "RelevanceClassification": "Low",

Justin's prompt - not considering location.
Variation 2

In [158]:
question = f''' You are an expert system used for classifying ConstructConnect projects based on relevance. 
Your task is to classify the provided project as very high, high, moderate, low, very low and not relevant to determine the likelihood of conversion to sales. 

**Instructions:**

1. **Analyze the provided JSON data** representing ConstructConnect projects to understand relevant fields and data.
2. **Utilize the Boolean filters** corresponding to each product category (provided below) to identify relevant keywords and phrases. 
A project is considered a match for a category if *any* of the keywords within the category's filter are found in the project data. 
Multiple occurrences of a keyword within a field should be counted as a single match. Case-insensitive matching should be performed.
3. **Classify projects:**
    * In stages indicating active procurement (e.g., "Biddate Set", "SUBBIDS: ASAP", "Post Bid", "Low Bids Announced").
    * Near the specified geographical area.
    * If all else is equal, assign higher priority to higher value projects.
4. **Estimate the relevancy of each project** based on the strength of product matches, project stage, proximity to specified geography, and total dollar amount. 
5. **Respond with a list of project evaluations** with an in-depth reasoning for relevancy rating (products, product categories, location, value etc.) in a valid JSON as provided in the Example Output below. Classify the projects as very high, high, moderate, low, very low and not relevant.


**JSON Project Data:** 
{cc_projects_json_records}

**Product Categories:**
{product_categories}

**Geographical Area:**
Chicago, IL

**Boolean Filters:**
{f_dict}


*Example Output:**
[
{{"ProjectID": 1006193703, "Relevance Classification": High, "Reasoning": "Product", "Product categories", "location", "value"}},
{{"ProjectID": 1006193700, "Relevance Classification": Low, "Reasoning": "Product", "Product categories", "location", "value"}}, 
{{"ProjectID": 1006193702, "Relevance Classification": Medium, "Reasoning": "Product", "Product categories", "location", "value"}}
]

'''

prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project is valued at $900,000.00, which is considered low for our products."
  },
  {
    "ProjectID": 1006877272,
    "Relevance Classification": "Very Low",
    "Reasoning": "While the project is in the 'General Contractor Award' stage, indicating active procurement, the project value of $200,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006887109,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, it's a large project with a value of $41,000,000.00, making it moderately relevant as it may have future opportunities for our products. The project is in Chicago, IL, within the specified geographical area."
  },
  {
    "ProjectID": 1006894126,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. It's a large project with a value of $86,400,000.00, but the early stage lowers its overall relevance."
  },
  {
    "ProjectID": 1006897214,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'General Contractor Award' stage, indicating active procurement. However, the project value of $10,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006877621,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $16,000,000.00 is moderately relevant for our products. It is in Chicago, IL, within the specified geographical area."
  },
  {
    "ProjectID": 1006877599,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $4,400,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007209685,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $500,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007202459,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, it's an addition project, not a new construction, which limits the potential for our products. The project value of $3,200,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007192557,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $32,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007196973,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $4,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007209015,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $7,800,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007207656,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $500,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007205490,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $1,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007202966,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $638,400.00 is too low for our products."
  },
  {
    "ProjectID": 1007191023,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is too early for product consideration. The project value of $11,693,200.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007209735,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $7,400,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007207472,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $6,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007198990,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $4,536,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007196854,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $500,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007203333,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Biddate Set' stage, indicating active procurement, and has a bid date of 2024-07-31. The project value of $3,000,000.00 is moderately relevant for our products. The project is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Automotive', which is a potential match for our Drywall Sales category due to the potential use of drywall in car wash facilities."
  },
  {
    "ProjectID": 1007209694,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $500,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007209689,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $500,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007183717,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. Also, the project value of $1,000,000.00 is considered low for our products."
  },
  {
    "ProjectID": 1007187083,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $205,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a 500-unit multi-residential development and a 70,875-square-foot retail development, both of which are likely to involve drywall."
  },
  {
    "ProjectID": 1007196975,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $3,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007196971,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $10,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007191661,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $2,500,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a multi-residential development and retail development, both of which are likely to involve drywall."
  },
  {
    "ProjectID": 1007191657,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $3,000,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Hospitals, Clinics', which is a potential match for our Drywall Sales category, as hospitals typically use drywall for interior walls. The project's 'Details_Detail_Scope' mentions the construction of a multi-residential development, a hotel, and retail development, all of which are likely to involve drywall."
  },
  {
    "ProjectID": 1006515488,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for product consideration. However, the project value of $140,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a 359-unit multi-residential development, which is likely to involve drywall for interior walls."
  },
  {
    "ProjectID": 1006514978,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $800,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006505800,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Duplicate Project' stage, indicating that it is not actively being pursued. The project value of $13,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1006504140,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $380,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006501300,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $1,290,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006509084,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $680,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006509056,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is too early for product consideration. The project value of $3,100,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006507328,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $1,007,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006497108,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $839,840.00 is too low for our products."
  },
  {
    "ProjectID": 1006495850,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $1,100,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007078163,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $5,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007088810,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $2,776,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007074366,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Duplicate Project' stage, indicating that it is not actively being pursued. The project value of $100,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007101212,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $7,000,000.00 is moderately relevant for our products. The project is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a 29-unit multi-residential development, which is likely to involve drywall."
  },
  {
    "ProjectID": 1007099481,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $40,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Manufacturing', which is a potential match for our Drywall Sales category due to the potential use of drywall in manufacturing facilities. The project's 'Details_Detail_Scope' mentions the addition of a 39,650-square-foot industrial development and the construction of a 61,950-square-foot industrial development, both of which are likely to involve drywall."
  },
  {
    "ProjectID": 1007101241,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is too early for product consideration. The project value of $33,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a 71-unit multi-residential development, which is likely to involve drywall for interior walls."
  },
  {
    "ProjectID": 1007094329,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $9,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007085411,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $9,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007085399,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is too early for product consideration. The project value of $65,000,000.00 is very relevant for our products. It is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a 210-unit multi-residential development, which is likely to involve drywall for interior walls."
  },
  {
    "ProjectID": 1007106384,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $2,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007079080,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, which is too early for product consideration. The project value of $15,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007095598,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $600,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007094751,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $1,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1007105988,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Post Bid' stage, indicating that the bid phase is complete. The project value of $75,000,000.00 is very relevant for our products. The project is in Chicago, IL, within the specified geographical area. The project's 'ParentCategories_PrimaryCategoryName' is 'Apartments', which is a potential match for our Drywall Sales category. The project's 'Details_Detail_Scope' mentions the construction of a six-story above grade multi-residential development, which is likely to involve drywall for interior walls."
  },
  {
    "ProjectID": 1007099533,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is too early for product consideration. The project value of $5,000,000.00 is moderately relevant for our products."
  },
  {
    "ProjectID": 1007094751,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is too early for any product consideration. The project value of $1,000,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006470732,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $380,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006485955,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $1,120,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006493256,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $380,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006493842,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'General Contractor Award' stage, indicating active procurement. However, the project value of $900,000.00 is too low for our products."
  },
  {
    "ProjectID": 1006493244,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is past the initial bid phase. However, the project value of $380,000.00 is too low for our products."

Variation 3- weighted prompt

In [159]:
question = f''' You are an expert system used for classifying ConstructConnect projects based on relevance. 
Your task is to classify the provided project as very high, high, moderate, low, very low and not relevant to determine the likelihood of conversion to sales. 

**Instructions:**

1. **Analyze the provided JSON data** representing ConstructConnect projects to understand relevant fields and data.
2. **Utilize the Boolean filters** corresponding to each product category (provided below) to identify relevant keywords and phrases. 
A project is considered a match for a category if *any* of the keywords within the category's filter are found in the project data. 
Multiple occurrences of a keyword within a field should be counted as a single match. Case-insensitive matching should be performed.
3. **Classify projects:**
    * In stages indicating active procurement (e.g., "Biddate Set", "SUBBIDS: ASAP", "Post Bid", "Low Bids Announced").
    * Near the specified geographical area.
    * If all else is equal, assign higher priority to higher value projects.
4. Using the **Relevance Score Calculation** calculate the score for each criteria- product matches, project stage, proximity to specified geography, and total dollar amount. 
5. Calculate **Total Relevance Score** = Sum of all criteria points. 
5. Using the **Relevance Classification** classify the projects as very high, high, moderate, low, very low and not relevant.
6. Respond with a list of project evaluations** with an in-depth reasoning for relevancy rating (products, product categories, location, value etc.) in a valid JSON as provided in the Example Output below. Classify the projects as very high, high, moderate, low, very low and not relevant.


**JSON Project Data:** 
{cc_projects_json_records}

**Product Categories:**
{product_categories}

**Geographical Area:**
Chicago, IL

**Boolean Filters:**
{f_dict}

**Relevance Score Calculation:**
*   Project Stage points: Bid Date Set: 5, Cancelled: 1, Construction Documents: 4, Construction Underway: 3, Design Development: 3, Disqualified Lead: 2, Duplicate Project: 0, General Contractor Award: 4, Low Bids Announced: 4, Post Bid: 3, Pre-Design: 1, Schematic Design: 2, SUBBIDS: ASAP: 5 
*   Product Matches points: High (5 points - substantial match), Medium (3 points - some matches), Low (1 point - few or no matches)
*   Proximity points: High (5 points - if the project is in the same state as **Geographical Area**), Medium (2 points - neighboring states), Low (1 point - other states)
*   Project Value points: Very High (5 points - above 4M USD), High (3 point - between 3M USD and 4M USD), Medium (2 points - between 2M USD and 3M USD), Low (1 point - below 2M USD)

**Total Relevance Score = Sum of all criteria points.

**Relevance Classification:**
* very high: Total Score >= 20
* high: Total Score >= 15 and < 20
* moderate: Total Score >= 10 and < 15
* low: Total Score >= 5 and < 10
* very low: Total Score < 5
* not relevant: Total Score = 0

*Example Output:**
[
{{"ProjectID": 1006193703, "Relevance Classification": High, "Reasoning": "Project Stage points, Product Matches points, Proximity points, Project Value points, total points"}},
{{"ProjectID": 1006193700, "Relevance Classification": Low, "Reasoning": "Project Stage points, Product Matches points, Proximity points, Project Value points, total points"}}, 
{{"ProjectID": 1006193702, "Relevance Classification": Medium, "Reasoning": "Project Stage points, Product Matches points, Proximity points, Project Value points, total points"}}
]

'''

prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 900,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 7, classifying the project as 'Very Low' relevance."
  },
  {
    "ProjectID": 1006877272,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which has a high relevance score of 4. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 200,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 10, classifying the project as 'Low' relevance."
  },
  {
    "ProjectID": 1006887109,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 41,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 18, classifying the project as 'Very High' relevance."
  },
  {
    "ProjectID": 1006894126,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 86,400,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 18, classifying the project as 'Very High' relevance."
  },
  {
    "ProjectID": 1006897214,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which has a high relevance score of 4. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 10,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006877621,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 16,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 18, classifying the project as 'Very High' relevance."
  },
  {
    "ProjectID": 1006877599,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which has a high relevance score of 4. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 4,400,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1007209685,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 500,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 7, classifying the project as 'Very Low' relevance."
  },
  {
    "ProjectID": 1007202459,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 3,200,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 13, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007192557,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 32,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 11, classifying the project as 'Low' relevance."
  },
  {
    "ProjectID": 1007196973,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 4,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 13, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007209015,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 7,800,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 13, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007207656,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 500,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 7, classifying the project as 'Very Low' relevance."
  },
  {
    "ProjectID": 1007205490,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 1,000,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 7, classifying the project as 'Very Low' relevance."
  },
  {
    "ProjectID": 1007202966,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 638,400 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1007191023,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Schematic Design' stage, which has a low relevance score of 2. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 11,693,200 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 12, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007209735,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which has a high relevance score of 4. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 7,400,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1007207472,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which has a high relevance score of 4. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 6,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1007196971,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 10,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 13, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007196975,
    "Relevance Classification": "Low",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 3,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 13, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1007191661,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 2,500,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 18, classifying the project as 'Very High' relevance."
  },
  {
    "ProjectID": 1007191657,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Design Development' stage, which has a medium relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 3,000,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 18, classifying the project as 'Very High' relevance."
  },
  {
    "ProjectID": 1006515488,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 140,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 16, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006514978,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 800,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006505800,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Duplicate Project' stage, which has a low relevance score of 0. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 13,000,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 15, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006504140,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 380,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006501300,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 1,290,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006497108,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 839,840 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006509084,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Pre-Design' stage, which has a low relevance score of 1. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 680,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 12, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1006509056,
    "Relevance Classification": "Very Low",
    "Reasoning": "The project is in the 'Schematic Design' stage, which has a low relevance score of 2. The project does not match any of the product categories, resulting in 0 product match points. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 3,100,000 USD, which is above 4M USD, resulting in a very high project value score of 5.  The total relevance score is 12, classifying the project as 'Moderate' relevance."
  },
  {
    "ProjectID": 1006507328,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 1,007,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006501357,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 300,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006495850,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Underway' stage, which has a high relevance score of 3. The project matches the 'Drywall Sales' category, resulting in a high product match score of 5. The project is located in Chicago, IL, which is the specified geographical area, giving it a high proximity score of 5. The project has a valuation of 1,100,000 USD, which is below 2M USD, resulting in a low project value score of 1.  The total relevance score is 14, classifying the project as 'High' relevance."
  },
  {
    "ProjectID": 1006495539,

Variation 4- Passing specific "Stage" list with wieghted prompt

In [160]:
stage_filter = {"high": ["Biddate Set", "Construction Documents", "General Contractor Award", "Low Bids Announced", "SUBBIDS: ASAP"], "moderate": ["Construction Underway", "Post Bid"], "ignore": ["Cancelled", "Design Development", "Disqualified Lead", "Duplicate Project", "Pre-Design", "Schematic Design"]}

In [161]:
## Gemini Prompt for ConstructConnect Project Classification
question = f'''
## ConstructConnect Project Classification

**Objective:** Classify ConstructConnect projects based on their likelihood of conversion to sales, providing a structured JSON output with relevance classification and detailed reasoning.

**Input:**

1. **Project Data (JSON):** A JSON object containing project information.  {cc_projects_json_records}

2. **Product Categories of Interest :** A list of strings representing the product categories. {product_categories}

3. **Boolean Filters:** A JSON object representing the boolean filters. {f_dict}

4. **Geographical Area of Interest :**  Chicago, IL, USA

5. **Target Project Stages:** A JSON object defining high, moderate and ignore stages. {stage_filter}


**Instructions:**

Analyze the provided project data and assign a relevancy rating (Very High, High, Moderate, Low, Very Low, Not Relevant) based on the criteria outlined below.  Provide a structured JSON output as shown in the example.

**Relevancy Criteria:**

* **Product Fit (Max 5 points):**
    * Project involves a product category of interest AND matches boolean filters: 5 points per category
    * Project involves a product category of interest but does NOT match boolean filters: 2 points per category
    * No relevant product categories: 0 points
* **Geographic Relevance (Max 3 points):**
    * Project's address StateProvince is within **Geographical Area of Interest**: 3 points
    * Project's address StateProvince is borders the **Geographical Area of Interest**: 1 point
    * Project's address StateProvince is outside and does not border the **Geographical Area of Interest**: 0 points
* **Project Stage (Max 5 points):**
    * High priority stage: 5 points
    * Moderate priority stage: 3 points
    * Stage to ignore: 0 points
* **Valuation (Max 3 points):**
    * High valuation (more than $5,000,000): 3 points
    * Medium valuation (between $3,000,000 to $5,000,000 USD): 2 points
    * Low valuation (between $1,000,000 to $3,000,000 ): 1 point
    * No valuation (lass than $1,000,000): 0 point


**Output:**

Return only a JSON object with the following structure:
```json
[{{
  "ProjectID": 1006193703,
  "Relevance Classification": "<relevancy_rating>",
  "Reasoning": "<detailed_reasoning_string>",
  "Product Fit Points": <product_fit_points>,
  "Geographic Relevance Points": <geographic_relevance_points>,
  "Project Stage Points": <project_stage_points>,
  "Valuation Points": <valuation_points>,
  "Total Points": <total_points>
}},
{{
  "ProjectID": 1006194567,
  "Relevance Classification": "<relevancy_rating>",
  "Reasoning": "<detailed_reasoning_string>",
  "Product Fit Points": <product_fit_points> ,
  "Geographic Relevance Points": <geographic_relevance_points> ,
  "Project Stage Points": <project_stage_points>,
  "Valuation Points": <valuation_points>,
  "Total Points": <total_points>
}},
...]
```

'''

prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1006877272,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which is a high priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 8
  },
  {
    "ProjectID": 1006887109,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 3,
    "Total Points": 9
  },
  {
    "ProjectID": 1006894126,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 6
  },
  {
    "ProjectID": 1006897214,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which is a high priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 1,
    "Total Points": 9
  },
  {
    "ProjectID": 1007209685,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007202459,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 1,
    "Total Points": 7
  },
  {
    "ProjectID": 1007192557,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007196973,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007209015,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007207656,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007202966,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1007205490,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007191023,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007196975,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007196971,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007207472,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 3,
    "Total Points": 13
  },
  {
    "ProjectID": 1007207320,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 10
  },
  {
    "ProjectID": 1007198990,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 10
  },
  {
    "ProjectID": 1007196854,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007209735,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 1,
    "Total Points": 11
  },
  {
    "ProjectID": 1007209694,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007209689,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007182734,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 6
  },
  {
    "ProjectID": 1007183717,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007187083,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1007191661,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a very high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1007191657,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a very high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1006515488,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 6
  },
  {
    "ProjectID": 1006514978,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006505800,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Duplicate Project' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1006504140,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006501300,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006509084,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1006509056,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1006507328,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006501357,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006497108,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006495850,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 0,
    "Total Points": 6
  },
  {
    "ProjectID": 1006495539,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is moderate priority. However, it does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 3,
    "Valuation Points": 3,
    "Total Points": 9
  },
  {
    "ProjectID": 1007078163,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 10
  },
  {
    "ProjectID": 1007088810,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007074366,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Duplicate Project' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007099481,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1007099533,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 10
  },
  {
    "ProjectID": 1007101212,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1007101241,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'Schematic Design' stage, which is ignored. However, it involves 'Drywall Sales' and matches the boolean filters, and has a high valuation.",
    "Product Fit Points": 5,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 11
  },
  {
    "ProjectID": 1007106384,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 0,
    "Total Points": 10
  },
  {
    "ProjectID": 1007079080,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 4
  },
  {
    "ProjectID": 1007095379,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is ignored. It also does not involve any product categories of interest.",
    "Product Fit Points": 0,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 0,
    "Valuation Points": 0,
    "Total Points": 3
  },
  {
    "ProjectID": 1007094329,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'Construction Documents' stage, which is a high priority. It involves 'Drywall Sales' but does not match the boolean filters.",
    "Product Fit Points": 2,
    "Geographic Relevance Points": 3,
    "Project Stage Points": 5,
    "Valuation Points": 1,
    "Total Points": 11
  },
  {
    "ProjectID": 1007085411,
    "Relevance Classification": "Not Relevant",

In [ ]:
# Columns to print
columns_to_print = ['ProjectID', 'Stage', 'Valuation_Value', 'ParentCategories_PrimaryCategoryName', 'ParentCategories_ParentCategory', 'Addresses_Address']

# Iterating through rows and printing selected columns
for index, row in cc_data_Subset.iterrows():
    values = [row[col] for col in columns_to_print]
    print(f"Row {index}: {', '.join(map(str, values))}")

Variation 5- Pre-filtering projects based on location instead of including in the prompt.

In [162]:
first_row_address = construct_connect_data.iloc[0]['Addresses_Address']
print(first_row_address)

[{'_ProjectAddressType': None, 'ns0:AddressLine1': '681 Springfield St', 'ns0:AddressLine2': None, 'ns0:City': 'Agawam', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:Latitude': Decimal('42.072375000'), 'ns0:Longitude': Decimal('-72.675163000'), 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01030'}]

In [163]:
city_name = "Chicago"
state_abbr = "IL"
zip_code_list = get_zip_codes(city_name, state_abbr)

In [167]:
location_specific_cc_data = construct_connect_data[construct_connect_data['Addresses_Address'].apply(lambda x: any(addr.get('ns0:ZipPostalCode') in zip_code_list for addr in x))]
location_specific_cc_data

,ProjectID,DataSourceID,Title,Stage,URL,UpdateDate,IsProspective,UpdateText,Valuation_Value,Valuation_Currency,Valuation_ValueType,Parameters_Parameter_Ownership,Parameters_Parameter_WorkType,Parameters_Parameter_CommenceDate,Parameters_Parameter_FloorArea,Parameters_Parameter_Structures,Parameters_Parameter_Units,Parameters_Parameter_BidDate,Parameters_Parameter_FloorAreaUnitofMeasure,Parameters_Parameter_IsSingleTrade,DocumentAvailability_Plans,DocumentAvailability_Specs,DocumentAvailability_Addenda,ParentCategories_PrimaryCategoryName,ParentCategories_ParentCategory,Addresses_Address,Contracts_Contract,ProjectEvents_ProjectEvent,Companies,Users,UpdateSummarizations_UpdateSummary,PlanSpecs,Details_Detail_Scope,Details_Detail_Notes,Details_Detail_Details,Details_Detail,Materials_Material,RSMeansMaterialDivisions_Division_Concrete,RSMeansMaterialDivisions_Division_Masonry,RSMeansMaterialDivisions_Division_Metals,RSMeansMaterialDivisions_Division_WoodPlasticsandComposites,RSMeansMaterialDivisions_Division_ThermalandMoistureProtection,RSMeansMaterialDivisions_Division_Openings,RSMeansMaterialDivisions_Division_Finishes,RSMeansMaterialDivisions_Division_Furnishings,RSMeansMaterialDivisions_Division_ConveyingEquipment,RSMeansMaterialDivisions_Division_FireSuppression,RSMeansMaterialDivisions_Division_Plumbing,RSMeansMaterialDivisions_Division_HeatingVentilatingandAirConditioningHVAC,RSMeansMaterialDivisions_Division_Electrical,RSMeansMaterialDivisions_Division_Communications,RSMeansMaterialDivisions_Division_ElectronicSafetyandSecurity,RSMeansMaterialDivisions_Division_Earthwork,RSMeansMaterialDivisions_Division_Utilities,Notes,ListDate,Connections,Parameters_Parameter_CompletionDate,Parameters_Parameter_MandatoryPreBidConferenceDate,RSMeansMaterialDivisions_Division_Specialties,RSMeansMaterialDivisions_Division_Equipment,Parameters_Parameter_FloorsAboveGround,RSMeansMaterialDivisions_Division_GeneralRequirements,RSMeansMaterialDivisions_Division_SpecialConstruction,Parameters_Parameter_LEEDCertificationIntent,Parameters_Parameter_ParkingSpaces,Parameters_Parameter_BidTime,Parameters_Parameter_FloorsBelowGround,ProjectParentID,Parameters_Parameter_SiteArea,Parameters_Parameter_SiteAreaUnitofMeasure,Parameters_Parameter_GreenBuildingCertification,Details_Detail_ContractConditions,Details,Details_Detail_Subbids,Details_Detail_Quantity_Unitprices,Parameters_Parameter_SingleTradeClassification,timeCreated,sourceFile,Notes_Note,Details_Detail_Status
1120,1006882884,US,Bojangles / Chicago,Pre-Design,http://insight.cmdgroup.com/SingleSignOn/Proje...,2024-02-16,False,Project Details or Scope was Added/Updated,900000.00,USD,Staff Estimate Value,Private,New,2025-09-05,NaN,1.0,NaN,None,None,False,False,False,False,Restaurants,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],[Site work and new construction of a restauran...,"[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],<NA>,2023-08-16,[],None,None,"[{'_': None, '_Code': None, '_InstallationCost...",[],NaN,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:50.699Z,1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml,[],[]
1121,1006877272,US,21st Street Multi-Residential,General Contractor Award,http://insight.cmdgroup.com/SingleSignOn/Proje...,2023-08-23,False,4-D Development was added as Design Build Cont...,200000.00,USD,Staff Estimate Value,Private,New,2023-08-28,NaN,2.0,3.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],"[Demolition, site work and new construction of...","[Development include(s): New Construction, De...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],<NA>,2023-08-23,[],None,None,[],[],3.0,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:50.699Z,1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml,[],[]
1122,1006887109,US,Michigan Avenue Mixed Use,Construction Underway,http://insight.cmdgroup.com/SingleSignOn/Proje...,2023-12-29,False,Brandts Build LLC was added as General Contractor,41000000.00,USD,Staff Estimate Value,Private,New,2023-11-29,NaN,4.0,149.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],"[Site work, paving and new construction of a m...","[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",<NA>,2023-08-30,[],None,None,[],[],13.0,[],[],None,98.0,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:50.699Z,1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml,[],[]
1123,1006894126,US,Westgate Development,Design Development,http://insight.cmdgroup.com/SingleSignOn/Proje...,2024-07-02,False,Updated to Design Development stage,86400000.00,USD,Confirmed Value,Private,New,2024-12-30,NaN,5.0,88.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],"[Site work, paving and new construction of a m...","[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",<NA>,2024-02-13,[],None,None,[],[],11.0,[],[],None,66.0,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:50.699Z,1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml,[],[]
1124,1006897214,US,Belmont Racine Apartments,General Contractor Award,http://insight.cmdgroup.com/SingleSignOn/Proje...,2024-01-03,False,"Project reviewed, Stage confirmed as General C...",10000000.00,USD,Staff Estimate Value,Private,New,2023-11-30,NaN,2.0,27.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],"[Demolition, site work and new construction of...","[Development include(s): New Construction, De...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",<NA>,2023-11-02,[],None,None,[],[],5.0,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:50.699Z,1.4_Adhoc_DL_FBMSales_XML_20241009_251.xml,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9096,1006489292,US,Indiana Avenue Residential Development,Construction Underway,http://insight.cmdgroup.com/SingleSignOn/Proje...,2022-09-01,False,"Allbright Construction, LLC was added as Gener...",450000.00,USD,Confirmed Value,Private,New,2022-08-23,NaN,1.0,3.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],[Site work and new construction of a multi-res...,"[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],<NA>,2022-09-01,[],None,None,[],[],3.0,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:51.139Z,1.4_Adhoc_DL_FBMSales_XML_20241009_277.xml,[],[]
9097,1006485984,US,Calumet Avenue Residential Development,Construction Underway,http://insight.cmdgroup.com/SingleSignOn/Proje...,2022-08-29,False,"Allbright Construction, LLC was added as Gener...",450000.00,USD,Confirmed Value,Private,New,2022-08-03,NaN,1.0,3.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],[Site work and new construction of a multi-res...,"[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",[],<NA>,2022-08-29,[],None,None,[],[],3.0,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:51.139Z,1.4_Adhoc_DL_FBMSales_XML_20241009_277.xml,[],[]
9098,1006470817,US,Aldine Avenue Residential Development,Construction Underway,http://insight.cmdgroup.com/SingleSignOn/Proje...,2022-08-19,False,Iuro & Associates was added as Architect,1600000.00,USD,Confirmed Value,Private,New,2022-08-01,NaN,1.0,6.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],[Site work and new construction of a multi-res...,"[Development include(s): New Construction, Si...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",<NA>,2022-08-19,[],None,None,[],[],4.0,[],[],None,NaN,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:51.139Z,1.4_Adhoc_DL_FBMSales_XML_20241009_277.xml,[],[]
9099,1006482617,US,Clark Street Residential Development,Construction Underway,http://insight.cmdgroup.com/SingleSignOn/Proje...,2024-06-10,False,Shutler Development Inc. was added as General ...,7000000.00,USD,Staff Estimate Value,Private,New,2023-06-05,NaN,5.0,18.0,None,None,False,False,False,False,Apartments,"[{'_Name': None, 'ns0:SubCategories': {'ns0:Su...","[{'_ProjectAddressType': None, 'ns0:AddressLin...",[],"[{'ns0:Event': 'Start Date', 'ns0:EventDate': ...","[{'ns0:Company': [{'_BiddingRole': None, '_Com...",[{'ns0:User': [{'_ProjectFlaggedForExport': No...,"[{'_Summary': None, '_UpdateSummaryDate': None...",[],"[Demolition, site work, paving and new constru...","[Development include(s): Demolition, Paving, ...",[],"[{'_': None, '_DetailType': None}, {'_': None,...",[],"[{'_': None, '_Code': None, '_InstallationCost...",[],"[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...","[{'_': None, '_Code': None, '_InstallationCost...",<NA>,2022-09-12,[],None,None,[],[],4.0,[],[],None,29.0,None,NaN,NaN,NaN,None,None,[],<NA>,[],[],None,2024-12-01T21:04:51.139Z,1.4_Adhoc_DL_FBMSales_XML_20241009_277.xml,[],[]

In [168]:
location_specific_subset = location_specific_cc_data[:5]
cc_projects_json_records = location_specific_subset.to_json(orient='records')

In [169]:
## Gemini Prompt for ConstructConnect Project Classification
question = f'''
## ConstructConnect Project Classification

**Objective:** Classify ConstructConnect projects based on their likelihood of conversion to sales, providing a structured JSON output with relevance classification and detailed reasoning.

**Input:**

1. **Project Data (JSON):** A JSON object containing project information.  {cc_projects_json_records}

2. **Product Categories of Interest :** A list of strings representing the product categories. {product_categories}

3. **Boolean Filters:** A JSON object representing the boolean filters. {f_dict}

4. **Target Project Stages:** A JSON object defining high, moderate and ignore stages. {stage_filter}


**Instructions:**

Analyze the provided project data and assign a relevancy rating (Very High, High, Moderate, Low, Very Low, Not Relevant) based on the criteria outlined below.  Provide a structured JSON output as shown in the example.

**Relevancy Criteria:**

* **Product Fit (Max 5 points):**
    * Project involves a product category of interest AND matches boolean filters: 5 points per category
    * Project involves a product category of interest but does NOT match boolean filters: 2 points per category
    * No relevant product categories: 0 points
* **Project Stage (Max 5 points):**
    * High priority stage: 5 points
    * Moderate priority stage: 3 points
    * Stage to ignore: 0 points
* **Valuation (Max 3 points):**
    * High valuation (more than $5,000,000): 3 points
    * Medium valuation (between $3,000,000 to $5,000,000 USD): 2 points
    * Low valuation (between $1,000,000 to $3,000,000 ): 1 point
    * No valuation (lass than $1,000,000): 0 point


**Output:**

Return only a JSON object with the following structure:
```json
[{{
  "ProjectID": 1006193703,
  "Relevance Classification": "<relevancy_rating>",
  "Reasoning": "<detailed_reasoning_string>",
  "Product Fit Points": <product_fit_points>,
  "Project Stage Points": <project_stage_points>,
  "Valuation Points": <valuation_points>,
  "Total Points": <total_points>
}},
{{
  "ProjectID": 1006194567,
  "Relevance Classification": "<relevancy_rating>",
  "Reasoning": "<detailed_reasoning_string>",
  "Product Fit Points": <product_fit_points> ,
  "Project Stage Points": <project_stage_points>,
  "Valuation Points": <valuation_points>,
  "Total Points": <total_points>
}},
...]
```

'''

prompt = question
contents = [prompt]

# Generate text using non-streaming method
response = model.generate_content(contents)

# Print generated text and usage metadata
print(f"\nAnswer:\n{response.text}")

Answer:
```json
[
  {
    "ProjectID": 1006882884,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Pre-Design' stage, which is categorized as 'ignore'. The project involves the 'Restaurants' category, which is not a product category of interest. The valuation is 900000.00 USD, which is low but does not contribute to relevancy because the stage is ignored.",
    "Product Fit Points": 0,
    "Project Stage Points": 0,
    "Valuation Points": 1,
    "Total Points": 1
  },
  {
    "ProjectID": 1006877272,
    "Relevance Classification": "High",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which is categorized as 'high'. The project involves the 'Apartments' category, which is not a product category of interest. The valuation is 200000.00 USD, which is low but does not negatively impact the relevancy because the stage is high.",
    "Product Fit Points": 0,
    "Project Stage Points": 5,
    "Valuation Points": 1,
    "Total Points": 6
  },
  {
    "ProjectID": 1006887109,
    "Relevance Classification": "Very High",
    "Reasoning": "The project is in the 'Construction Underway' stage, which is categorized as 'moderate'. The project involves the 'Apartments', 'Roads', and 'Retail Stores' categories, none of which are product categories of interest. However, the valuation is 41000000.00 USD, which is high, and the stage is moderate, resulting in a 'Very High' relevance classification.",
    "Product Fit Points": 0,
    "Project Stage Points": 3,
    "Valuation Points": 3,
    "Total Points": 6
  },
  {
    "ProjectID": 1006894126,
    "Relevance Classification": "Not Relevant",
    "Reasoning": "The project is in the 'Design Development' stage, which is categorized as 'ignore'. The project involves the 'Roads', 'Offices', 'Apartments', 'Townhomes', 'Food Stores', and 'Restaurants' categories, none of which are product categories of interest. The valuation is 86400000.00 USD, which is high, but does not contribute to relevancy because the stage is ignored.",
    "Product Fit Points": 0,
    "Project Stage Points": 0,
    "Valuation Points": 3,
    "Total Points": 3
  },
  {
    "ProjectID": 1006897214,
    "Relevance Classification": "Moderate",
    "Reasoning": "The project is in the 'General Contractor Award' stage, which is categorized as 'high'. The project involves the 'Apartments' and 'Automotive' categories, which are not product categories of interest. The valuation is 10000000.00 USD, which is high, but does not result in a 'High' relevance classification because the project does not involve product categories of interest.",
    "Product Fit Points": 0,
    "Project Stage Points": 5,
    "Valuation Points": 3,
    "Total Points": 8
  }
]
```

In [170]:
# Columns to print
columns_to_print = ['ProjectID', 'Stage', 'Valuation_Value', 'ParentCategories_PrimaryCategoryName', 'ParentCategories_ParentCategory', 'Addresses_Address']

# Iterating through rows and printing selected columns
for index, row in location_specific_subset.iterrows():
    values = [row[col] for col in columns_to_print]
    print(f"Row {index}: {', '.join(map(str, values))}")

Row 1120: 1006882884, Pre-Design, 900000.00, Restaurants, [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Restaurants'], dtype=object)}}], [{'_ProjectAddressType': None, 'ns0:AddressLine1': 'To Be Determined', 'ns0:AddressLine2': None, 'ns0:City': 'Chicago', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Cook', 'ns0:Latitude': Decimal('41.875734000'), 'ns0:Longitude': Decimal('-87.625562000'), 'ns0:StateProvince': 'IL', 'ns0:ZipPostalCode': '60604'}]
Row 1121: 1006877272, General Contractor Award, 200000.00, Apartments, [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Apartments'], dtype=object)}}], [{'_ProjectAddressType': None, 'ns0:AddressLine1': '1952 W 21st St', 'ns0:AddressLine2': None, 'ns0:City': 'Chicago', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Cook', 'ns0:Latitude': Decimal('41.849103000'), 'ns0:Longitude': Decimal('-87.667335000'), 'ns0:StateProvince': 'IL', 'ns0:ZipPostalCode': '60608'}]
Row 1122: 1006887109, Construction Underway, 41000000.00, Apartments, [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Roads'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Apartments'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Retail Stores'], dtype=object)}}], [{'_ProjectAddressType': None, 'ns0:AddressLine1': '1723 S Michigan Ave', 'ns0:AddressLine2': None, 'ns0:City': 'Chicago', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Cook', 'ns0:Latitude': Decimal('41.844775000'), 'ns0:Longitude': Decimal('-87.626719000'), 'ns0:StateProvince': 'IL', 'ns0:ZipPostalCode': '60616'}]
Row 1123: 1006894126, Design Development, 86400000.00, Apartments, [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Roads'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Offices'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Apartments', 'Townhomes'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Food Stores', 'Restaurants'], dtype=object)}}], [{'_ProjectAddressType': None, 'ns0:AddressLine1': '3811 W Madison St', 'ns0:AddressLine2': None, 'ns0:City': 'Chicago', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Cook', 'ns0:Latitude': Decimal('41.877445000'), 'ns0:Longitude': Decimal('-87.723846000'), 'ns0:StateProvince': 'IL', 'ns0:ZipPostalCode': '60624'}]
Row 1124: 1006897214, General Contractor Award, 10000000.00, Apartments, [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Apartments'], dtype=object)}}
 {'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': array(['Automotive'], dtype=object)}}], [{'_ProjectAddressType': None, 'ns0:AddressLine1': '3202 N Racine Ave', 'ns0:AddressLine2': None, 'ns0:City': 'Chicago', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Cook', 'ns0:Latitude': Decimal('41.940734000'), 'ns0:Longitude': Decimal('-87.654198000'), 'ns0:StateProvince': 'IL', 'ns0:ZipPostalCode': '60657'}]