In [31]:
import pandas as pd

In [32]:
df_single_prompt_output = pd.read_csv('data/single_prompt_output.csv')
df_single_prompt_output

,ProjectID,Product,Product priority,Materials matching,Relevance Classification,Reasoning
0,1006872527,3M Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",low,Project is a police department addition/renova...
1,1006872527,Access Door Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",moderate,The project involves addition and renovation o...
2,1006872527,Ceiling Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'D...",very high,Project includes 'Addition / Renovation' work ...
3,1006872527,Certainteed Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,Project description contains 'renovation and a...
4,1006872527,Cultured Stone Sales,low,"['Stone', 'Waterproofing', 'Metal Doors', 'Met...",moderate,The project is a renovation and addition to a ...
5,1006872527,Drywall Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,The project involves an addition/renovation to...
6,1006872527,EIFS & Stucco Sales,high,"['Waterproofing', 'Insulation', 'Firestopping'...",high,Project includes renovation and addition to a ...
7,1006872527,FRP Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",High,The project is a police station addition/renov...
8,1006872527,Fry Reglet Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'A...",high,The project involves addition and renovation o...
9,1006872527,Georgia Pacific Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,The project involves addition/renovation work ...
10,1006872527,Insulation Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",very high,Project involves addition and renovation of a ...
11,1006872527,Nichiha Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",moderate,Project is an addition/renovation of a police ...
12,1006872527,Pabco Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'A...",high,Project involves addition/renovation. Many rel...
13,1006872527,Steel Sales,high,"['Cold Formed Metal Framing', 'Metal Decking',...",very high,This project involves the addition and renovat...
14,1006879795,3M Sales,low,"['Lath & Plaster', 'Concrete Reinforcement', '...",low,Project is an apartment complex construction. ...
15,1006879795,Access Door Sales,low,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",low,The project is an apartment complex with a com...
16,1006879795,Ceiling Sales,high,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,The project involves apartment construction. I...
17,1006879795,Certainteed Drywall Sales,low,"['Acoustical Ceilings', 'Cold Formed Metal Fra...",high,"Project involves apartment construction, which..."
18,1006879795,Cultured Stone Sales,low,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,Project includes 'stone' and 'concrete' in pro...
19,1006879795,Drywall Sales,high,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,"The project is an apartment complex, which typ..."
20,1006879795,EIFS & Stucco Sales,high,"['Lath & Plaster', 'Concrete', 'Water Systems'...",moderate,The project is a multi-residential development...
21,1006879795,FRP Sales,high,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,Project is an apartment complex which often us...
22,1006879795,Fry Reglet Sales,high,"['Concrete Formwork', 'Concrete Reinforcement'...",Moderate,"The project is an apartment complex, which cou..."
23,1006879795,Georgia Pacific Drywall Sales,low,"['Lath & Plaster', 'Gypsum Board', 'Insulation...",moderate,The project is an apartment complex with concr...
24,1006879795,Insulation Sales,high,"['Lath & Plaster', 'Insulation', 'Concrete For...",high,The project description includes details relat...
25,1006879795,Nichiha Sales,high,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,Project is an apartment complex which is likel...
26,1006879795,Pabco Drywall Sales,low,"['Lath & Plaster', 'Concrete Formwork', 'Concr...",moderate,Project is an apartment complex under construc...
27,1006879795,Steel Sales,high,"['Concrete Reinforcement', 'Ductwork', 'Exteri...",moderate,The project is an apartment complex which can ...
28,1006891936,3M Sales,low,[],not relevant,The project description does not contain any k...
29,1006891936,Access Door Sales,low,['Metal Doors'],moderate,The project involves renovation of a courthous...
30,1006891936,Ceiling Sales,high,[],moderate,Project involves renovation of a courthouse in...
31,1006891936,Certainteed Drywall Sales,low,"['Drywall/Gypsum', 'Insulation', 'Lath & Plast...",moderate,The project is a courthouse renovation that in...
32,1006891936,Cultured Stone Sales,low,"['Stone Masonry', 'Masonry']",moderate,The project involves renovation with masonry r...
33,1006891936,Drywall Sales,high,[],moderate,The project involves renovation of a courthous...
34,1006891936,EIFS & Stucco Sales,high,"['Stucco', 'Lath & Plaster']",moderate,Project is a courthouse renovation including m...
35,1006891936,FRP Sales,high,[],low,The project is a courthouse renovation includi...
36,1006891936,Fry Reglet Sales,high,"['Metal Doors', 'Lath & Plaster', 'Drywall/Gyp...",moderate,The project involves renovation of a courthous...
37,1006891936,Georgia Pacific Drywall Sales,low,"['Roofing & Flashing', 'Insulation', 'Fireproo...",low,The project is a renovation of a courthouse in...
38,1006891936,Insulation Sales,high,"['Insulation', 'Firestopping']",moderate,The project involves renovation of a courthous...
39,1006891936,Nichiha Sales,high,"['Masonry', 'Roofing', 'Electrical', 'HVAC']",low,"Project involves masonry, roofing, HVAC, and e..."
40,1006891936,Pabco Drywall Sales,low,"['Drywall/Gypsum', 'Metal Doors']",moderate,The project involves renovation including inte...
41,1006891936,Steel Sales,high,"['Masonry', 'Roofing', 'Metals']",moderate,The project involves renovation of a courthous...

In [33]:
df_multi_prompt_output = pd.read_csv('data/second_pass_output.csv')
df_multi_prompt_output

,ProjectID,Product,Product priority,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation,Reason,Project priority,Reasoning,Relevance Classification,Classification Reasoning
0,1006872527,3M Sales,low,NO,The project details and associated companies d...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
1,1006872527,Access Door Sales,low,NO,The provided project data does not contain any...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
2,1006872527,Ceiling Sales,high,YES,The 'Details_Detail_Scope' field mentions 'CEI...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,very high,The project is related to Ceiling Sales and is...
3,1006872527,Certainteed Drywall Sales,low,YES,The 'Details_Detail_Details' field contains 'D...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...
4,1006872527,Cultured Stone Sales,low,YES,The Detail_Detail_Scope mentions 'Stone' as a ...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,"The project valuation is high, and it contains..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1006879672,Georgia Pacific Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"['Cold Formed Metal Framing', 'Metal Decking',...",The project description and details mention 'C...,5249000.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...
136,1006879672,Insulation Sales,high,YES,The 'Details_Detail_Details' field contains 'I...,YES,"['Cold Formed Metal Framing', 'Metal Decking',...",The project description and details mention 'C...,5249000.0,NaN,NaN,NaN,very high,The project includes Insulation (the product i...
137,1006879672,Nichiha Sales,high,NO,The provided project data does not contain any...,YES,"['Cold Formed Metal Framing', 'Metal Decking',...",The project description and details mention 'C...,5249000.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
138,1006879672,Pabco Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"['Cold Formed Metal Framing', 'Metal Decking',...",The project description and details mention 'C...,5249000.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...
139,1006879672,Steel Sales,high,YES,The project details mention 'Structural Steel'...,YES,"['Cold Formed Metal Framing', 'Metal Decking',...",The project description and details mention 'C...,5249000.0,NaN,NaN,NaN,very high,The project aligns with the 'Steel Sales' prod...

In [34]:
merged_df = pd.merge(df_single_prompt_output, df_multi_prompt_output, on=['ProjectID', 'Product'], suffixes=('_single', '_multi'), how='outer')
merged_df

,ProjectID,Product,Product priority_single,Materials matching,Relevance Classification_single,Reasoning_single,Product priority_multi,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation,Reason,Project priority,Reasoning_multi,Relevance Classification_multi,Classification Reasoning
0,1006872527,3M Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",low,Project is a police department addition/renova...,low,NO,The project details and associated companies d...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
1,1006872527,Access Door Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",moderate,The project involves addition and renovation o...,low,NO,The provided project data does not contain any...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
2,1006872527,Ceiling Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'D...",very high,Project includes 'Addition / Renovation' work ...,high,YES,The 'Details_Detail_Scope' field mentions 'CEI...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,very high,The project is related to Ceiling Sales and is...
3,1006872527,Certainteed Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,Project description contains 'renovation and a...,low,YES,The 'Details_Detail_Details' field contains 'D...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...
4,1006872527,Cultured Stone Sales,low,"['Stone', 'Waterproofing', 'Metal Doors', 'Met...",moderate,The project is a renovation and addition to a ...,low,YES,The Detail_Detail_Scope mentions 'Stone' as a ...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,"The project valuation is high, and it contains..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1006891936,Georgia Pacific Drywall Sales,low,"['Roofing & Flashing', 'Insulation', 'Fireproo...",low,The project is a renovation of a courthouse in...,low,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
136,1006891936,Insulation Sales,high,"['Insulation', 'Firestopping']",moderate,The project involves renovation of a courthous...,high,YES,The project scope includes HVAC work and roofi...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,low,"The project is related to Insulation Sales, wh..."
137,1006891936,Nichiha Sales,high,"['Masonry', 'Roofing', 'Electrical', 'HVAC']",low,"Project involves masonry, roofing, HVAC, and e...",high,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
138,1006891936,Pabco Drywall Sales,low,"['Drywall/Gypsum', 'Metal Doors']",moderate,The project involves renovation including inte...,low,NO,The project data does not contain any mention ...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...
139,1006891936,Steel Sales,high,"['Masonry', 'Roofing', 'Metals']",moderate,The project involves renovation of a courthous...,high,YES,The project details mention 'Miscellaneous & O...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,The project includes 'Masonry' and 'Roofing' m...

In [35]:
merged_df['match'] = merged_df['Relevance Classification_single'] == merged_df['Relevance Classification_multi']
merged_df

,ProjectID,Product,Product priority_single,Materials matching,Relevance Classification_single,Reasoning_single,Product priority_multi,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation,Reason,Project priority,Reasoning_multi,Relevance Classification_multi,Classification Reasoning,match
0,1006872527,3M Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",low,Project is a police department addition/renova...,low,NO,The project details and associated companies d...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
1,1006872527,Access Door Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",moderate,The project involves addition and renovation o...,low,NO,The provided project data does not contain any...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
2,1006872527,Ceiling Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'D...",very high,Project includes 'Addition / Renovation' work ...,high,YES,The 'Details_Detail_Scope' field mentions 'CEI...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,very high,The project is related to Ceiling Sales and is...,True
3,1006872527,Certainteed Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,Project description contains 'renovation and a...,low,YES,The 'Details_Detail_Details' field contains 'D...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...,False
4,1006872527,Cultured Stone Sales,low,"['Stone', 'Waterproofing', 'Metal Doors', 'Met...",moderate,The project is a renovation and addition to a ...,low,YES,The Detail_Detail_Scope mentions 'Stone' as a ...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,"The project valuation is high, and it contains...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1006891936,Georgia Pacific Drywall Sales,low,"['Roofing & Flashing', 'Insulation', 'Fireproo...",low,The project is a renovation of a courthouse in...,low,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
136,1006891936,Insulation Sales,high,"['Insulation', 'Firestopping']",moderate,The project involves renovation of a courthous...,high,YES,The project scope includes HVAC work and roofi...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,low,"The project is related to Insulation Sales, wh...",False
137,1006891936,Nichiha Sales,high,"['Masonry', 'Roofing', 'Electrical', 'HVAC']",low,"Project involves masonry, roofing, HVAC, and e...",high,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
138,1006891936,Pabco Drywall Sales,low,"['Drywall/Gypsum', 'Metal Doors']",moderate,The project involves renovation including inte...,low,NO,The project data does not contain any mention ...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
139,1006891936,Steel Sales,high,"['Masonry', 'Roofing', 'Metals']",moderate,The project involves renovation of a courthous...,high,YES,The project details mention 'Miscellaneous & O...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,The project includes 'Masonry' and 'Roofing' m...,False

In [36]:
merged_df['match'] = merged_df['match'].fillna(False)  # Treat NaN as not matching
merged_df

,ProjectID,Product,Product priority_single,Materials matching,Relevance Classification_single,Reasoning_single,Product priority_multi,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation,Reason,Project priority,Reasoning_multi,Relevance Classification_multi,Classification Reasoning,match
0,1006872527,3M Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",low,Project is a police department addition/renova...,low,NO,The project details and associated companies d...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
1,1006872527,Access Door Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",moderate,The project involves addition and renovation o...,low,NO,The provided project data does not contain any...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
2,1006872527,Ceiling Sales,high,"['Acoustical Ceilings', 'Acoustical Walls', 'D...",very high,Project includes 'Addition / Renovation' work ...,high,YES,The 'Details_Detail_Scope' field mentions 'CEI...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,very high,The project is related to Ceiling Sales and is...,True
3,1006872527,Certainteed Drywall Sales,low,"['Acoustical Ceilings', 'Acoustical Walls', 'C...",high,Project description contains 'renovation and a...,low,YES,The 'Details_Detail_Details' field contains 'D...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,The project includes multiple relevant materia...,False
4,1006872527,Cultured Stone Sales,low,"['Stone', 'Waterproofing', 'Metal Doors', 'Met...",moderate,The project is a renovation and addition to a ...,low,YES,The Detail_Detail_Scope mentions 'Stone' as a ...,YES,"['Waterproofing', 'Metal Doors', 'Acoustical C...","The project details mention 'Waterproofing', '...",4637163.0,NaN,NaN,NaN,moderate,"The project valuation is high, and it contains...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,1006891936,Georgia Pacific Drywall Sales,low,"['Roofing & Flashing', 'Insulation', 'Fireproo...",low,The project is a renovation of a courthouse in...,low,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
136,1006891936,Insulation Sales,high,"['Insulation', 'Firestopping']",moderate,The project involves renovation of a courthous...,high,YES,The project scope includes HVAC work and roofi...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,low,"The project is related to Insulation Sales, wh...",False
137,1006891936,Nichiha Sales,high,"['Masonry', 'Roofing', 'Electrical', 'HVAC']",low,"Project involves masonry, roofing, HVAC, and e...",high,NO,The provided project data does not contain any...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
138,1006891936,Pabco Drywall Sales,low,"['Drywall/Gypsum', 'Metal Doors']",moderate,The project involves renovation including inte...,low,NO,The project data does not contain any mention ...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,Project is not related to the product or relev...,False
139,1006891936,Steel Sales,high,"['Masonry', 'Roofing', 'Metals']",moderate,The project involves renovation of a courthous...,high,YES,The project details mention 'Miscellaneous & O...,YES,"['Masonry', 'Roofing']",The 'Details_Detail_Scope' field mentions 'exi...,4093126.0,NaN,NaN,NaN,not relevant,The project includes 'Masonry' and 'Roofing' m...,False

In [37]:
merged_df['match'].sum()

np.int64(7)

In [38]:
len(merged_df) - merged_df['match'].sum()

np.int64(133)

In [39]:
merged_df.to_csv('data/merged_output.csv', index=False)