In [116]:
import pandas as pd
from vertexai.generative_models import (
    FunctionDeclaration,
    GenerationConfig,
    GenerativeModel,
    Tool,
    HarmCategory,
    HarmBlockThreshold
)
import json
import re

In [117]:
import import_ipynb
from filters import get_all_filters

get Boolean filters, relevant stages and relevant materials

In [118]:
boolean_filter_json, stage_filter, materials  = get_all_filters()
product_filter_json = json.loads(boolean_filter_json)

Get a sample of ConstructConnect Data

In [119]:
construct_connect_data = pd.read_pickle('data/construct_connect_data.pkl')

Filter by stage

In [120]:
stages_to_include = stage_filter["high"] + stage_filter["moderate"]
filtered_by_stage = construct_connect_data[construct_connect_data['Stage'].isin(stages_to_include)]

Filter by Value

In [121]:
if filtered_by_stage['Valuation_Value'].dtype == 'object':  # Check if it's a string (object type)
    filtered_by_stage.loc[:, 'Valuation_Value'] = pd.to_numeric(filtered_by_stage.loc[:, 'Valuation_Value'], errors='coerce')
filtered_cc_data = filtered_by_stage[filtered_by_stage['Valuation_Value'] > 1000000]

In [122]:
filtered_cc_data[:200].to_csv('data/filtered_cc_data.csv', index=False)

In [123]:
cc_data_subset = filtered_cc_data[:3]

Gemini Flash 2.0

In [124]:
PROJECT_ID = "proj-sales-recommender-dev"
LOCATION = "us-central1" 

import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

In [125]:
MODEL_ID = "gemini-2.0-flash-001"

model = GenerativeModel(
    MODEL_ID,
    safety_settings={
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
        },

)

Single query

In [126]:
def run_prompt(product, search_query, cc_project_json, materials, product_priority):
    question = f'''

    **Objective:** Classify ConstructConnect projects as very high, high, moderate, low, very low and not relevant.

    

    **Instructions:**

    1. **Analyze the provided JSON data** representing ConstructConnect projects to understand relevant fields and data.
    2. **Utilize the Search Query** corresponding to the product (provided below) to identify if project is related to the given product.
    3. **Utilize the relevant materials** to identify if the project has any of the materials listed.
    4. **Utilize the product priority** to weigh the classifying attributes accordingly.
    4. **Classify projects:**
        * With a project description that includes the product category or related terms.
        * Where the product query matches across mutliple project fields.
        * Containing sunstantial number of matching materials from the **Relevant Materials** list.
        * Based on the Product Priority and project-product relationship.
        * If all else is equal, assign higher priority to higher value projects.
    4. **Estimate the relevancy of each project** based on product matches, materials and total dollar amount. 
    5. **Respond with a list of project evaluations** in valid JSON as provided in the Example Output below. Classify the projects as very high, high, moderate, low, very low and not relevant. RETURN ONLY THE JSON RESPONSE.


    **JSON Project Data:** 
    {cc_project_json}

    **Product Category:**
    {product}

    **Boolean Filter for the Product:**
    {search_query}

    **Relevant Materials:**
    {materials}

    ** Product Priority:**
    {product_priority}

    **Example Output:**
    {{"ProjectID": 1006193703,"Product": {product}, "Product priority":{product_priority}, "Materials matching": [material1, material2, material3],  "Relevance Classification": High, "Reasoning": reason for classification}}

    '''

    prompt = question
    contents = [prompt]

    # Generate text using non-streaming method
    response = model.generate_content(contents)

    # Print generated text and usage metadata
    #print(f"\nAnswer:\n{response.text}")
    return response.text

In [127]:
product_responses = []
for index, row in cc_data_subset.iterrows():  # Iterate through rows
    row_json_str = row.to_json()  # Convert row to dictionary
    cc_project_json_record = json.loads(row_json_str) 
    for item in product_filter_json:
        output = run_prompt(item['Filter'], item['Query'], cc_project_json_record, materials, item['Priority'] )
        otpt = output.replace("```json", "").replace("```", "")
        product_responses.append(otpt)

In [128]:
product_responses

['\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "3M Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "low",\n    "Reasoning": "Project is a police department addition/renovation. While it includes several relevant materials such as Acoustical Ceilings, Drywall, Metal Doors and Firestopping, the product \'3M Sales\' doesn\'t have a strong direct association. The project includes \'Addition / Renovation\' which indicates relevance but product priority is low. No explicit mention of 3M products."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Access Door Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project involves addition and renovation of a fire/police facility, where metal doors, insulation, acoustical ceilings and walls, drywall, and waterproofing are relevant materials to access door sales. There isn\'t a direct mention of access doors but the listed materials and work type suggest a moderate relevance. Bids were also recieved from Avid Ironworks, which could also be related."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Ceiling Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Cold Formed Metal Framing",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "very high",\n    "Reasoning": "Project includes \'Addition / Renovation\' work with multiple matching materials (Acoustical Ceilings, Acoustical Walls, Drywall, etc.) and mentions ceilings specifically as a sub-bid. Several companies associated with the project specialize in ceiling installation. The search query also has matches within the project details. The project valuation is also high."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Certainteed Drywall Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "Project description contains \'renovation and addition\' and multiple relevant materials are listed in division breakdowns, specifically drywall/gypsum, acoustical ceilings/walls, insulation, metal decking, metal doors, waterproofing and lath and plaster. Also, Capital Carpet is listed in the Details Scope."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Cultured Stone Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Stone",\n      "Waterproofing",\n      "Metal Doors",\n      "Metal Framing",\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Drywall/Gypsum",\n      "Lath & Plaster",\n      "Insulation",\n      "Firestopping"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project is a renovation and addition to a fire/police facility. The project description mentions \'Stone\' in the context of building materials. Multiple relevant materials were identified.  However, given the low product priority and the general nature of the project, the relevance is moderate."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Drywall Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "The project involves an addition/renovation to a police department, with a confirmed value of $4,637,163. The project details mention \'Drywall/Gypsum\', \'Acoustical Ceilings\', \'Acoustical Walls\', \'Cold Formed Metal Framing\', \'Firestopping\', \'Insulation\', \'Lath & Plaster\', \'Metal Decking\', \'Metal Doors\', \'Waterproofing\', indicating a strong relevance to drywall sales and related materials. The product priority is high, further increasing the classification."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "EIFS & Stucco Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Waterproofing",\n      "Insulation",\n      "Firestopping",\n      "Metal Doors",\n      "Acoustical Ceilings",\n      "Carpet",\n      "Painting",\n      "Drywall/Gypsum",\n      "Lath & Plaster",\n      "Ceiling Suspension Systems",\n      "Metal Doors",\n      "Structural Steel",\n      "Metal Decking",\n      "Cold Formed Metal Framing",\n      "Stone"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "Project includes renovation and addition to a police and fire station, indicating significant construction work.  The project description mentions \'WATERPROOFING:Armani Restoration\', \'ROOFING:Silktown Roofing\' ,CEILINGS:Rocky\'s Acoustics,$105,000.00 FLOORING:Capital Carpet\' which are all in materials matching list.  The division details also include materials from the boolean filter like \'Exterior Insulation & Finish Systems, Shingles, Manufactured Roofing & Siding, Membrane Roofing\', the mention of \'Division 7: Waterproofing, Insulation, Exterior Insulation & Finish Systems, Firestopping, Shingles, Manufactured Roofing & Siding, Membrane Roofing\' also suggests a high relevance, and the project valuation is relatively high."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "FRP Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "High",\n    "Reasoning": "The project is a police station addition/renovation.  The project details contain relevant keywords (\'FRP\') and a substantial number of relevant materials are present in the project details, making it highly relevant to FRP Sales with high product priority.  The estimated cost is also significant."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Fry Reglet Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Architectural Woodwork",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "The project involves addition and renovation of a police station which typically requires interior finishes, including acoustical ceilings and walls, drywall, and carpentry, matching multiple relevant materials. Also has relevant keywords of millwork within details. The valuation is also high."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Georgia Pacific Drywall Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "The project involves addition/renovation work and the details mention several relevant materials like \'Acoustical Ceilings\', \'Acoustical Walls\', \'Cold Formed Metal Framing\', \'Drywall/Gypsum\', \'Firestopping\', \'Insulation\', \'Lath & Plaster\', \'Metal Decking\', \'Metal Doors\', and \'Waterproofing\'.  The project value is also substantial ($4.6M). The presence of Drywall/Gypsum, coupled with multiple other relevant materials, justifies a high classification despite the low product priority."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Insulation Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "very high",\n    "Reasoning": "Project involves addition and renovation of a fire/police facility. The project details mention several relevant materials including Acoustical Ceilings, Acoustical Walls, Cold Formed Metal Framing, Drywall/Gypsum, Firestopping, Insulation, Lath & Plaster, Metal Decking, Metal Doors and waterproofing indicating substantial insulation needs.  Also \'Silktown Roofing\' bid, implying roofing insulation could be used. Project valuation is significant ($4.6M) which can be very high for insulation sales"\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Nichiha Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "Project is an addition/renovation of a police department.  Although the boolean query does not match, the quantity of relevant materials and the fact that the project is an addition/renovation of a police station, the project shows moderate relevance."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Pabco Drywall Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Architectural Woodwork",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Firestopping",\n      "Insulation",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Metal Doors",\n      "Waterproofing"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "Project involves addition/renovation. Many relevant materials are present (Acoustical Ceilings, Acoustical Walls, Architectural Woodwork, Cold Formed Metal Framing, Drywall/Gypsum, Firestopping, Insulation, Lath & Plaster, Metal Decking, Metal Doors, Waterproofing).  Division details mention drywall and acoustical ceilings directly. The size of the project $4,637,163 also increases relevance."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006872527,\n    "Product": "Steel Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Cold Formed Metal Framing",\n      "Metal Decking",\n      "Structural Steel",\n      "Metal Doors",\n      "Ceiling Suspension Systems",\n      "Lath & Plaster",\n      "Drywall/Gypsum",\n      "Acoustical Ceilings",\n      "Acoustical Walls",\n      "Firestopping",\n      "Waterproofing",\n       "Structural Metal Stud Framing",\n      "Steel Decking",\n      "Structural Steel Framing",\n      "Metal Doors And Frames"\n    ],\n    "Relevance Classification": "very high",\n    "Reasoning": "This project involves the addition and renovation of a fire/police facility and includes a wide array of steel-related materials like metal framing, decking and doors, as well as lath, plaster, and drywall for internal structure and finishes. The project also includes fire protection and suppression systems indicating substantial steel usage. Many steel related keywords match from the search query. High project value also contributes to the high classification."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "3M Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Reinforcement",\n      "Structural Concrete",\n      "Concrete Formwork",\n      "Ductwork"\n    ],\n    "Relevance Classification": "low",\n    "Reasoning": "Project is an apartment complex construction. While it includes \'Lath & Plaster, Concrete Reinforcement, Structural Concrete, Concrete Formwork and Ductwork\' from the Relevant Materials list, it does not specifically mention 3M or related products. Given the low product priority, the absence of a direct product match leads to a low classification."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Access Door Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete",\n      "Ductwork",\n      "Exterior Lighting"\n    ],\n    "Relevance Classification": "low",\n    "Reasoning": "The project is an apartment complex with a community center. The project details mention \'Lath & Plaster\' and \'ductwork\'. While these materials are relevant, there\'s no explicit mention of access doors or related terms from the boolean filter in the project description.  Given the low product priority and lack of strong indicators, the project is classified as low relevance."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Ceiling Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project involves apartment construction. It has a decent valuation ($60M). Includes Lath & Plaster, Concrete Formwork, Concrete Reinforcement, Structural Concrete from the Relevant Materials list.  However, no explicit mention of ceiling products from boolean filter in the description. Details include division 9 which covers Lath & Plaster"\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Certainteed Drywall Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Acoustical Ceilings",\n      "Cold Formed Metal Framing",\n      "Drywall/Gypsum",\n      "Lath & Plaster",\n      "Metal Decking",\n      "Insulation",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete"\n    ],\n    "Relevance Classification": "high",\n    "Reasoning": "Project involves apartment construction, which commonly uses drywall.  Multiple materials related to drywall and associated construction are listed. The project is valued at $60,000,000. While product priority is low, the substantial dollar value of project combined with materials means high opportunity."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Cultured Stone Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "Project includes \'stone\' and \'concrete\' in project details and is relevant to materials. Meets search query and the category apartments suggest possible use for interior. Low product priority and already underway reduce the significance."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Drywall Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project is an apartment complex, which typically uses drywall.  The \'Details_Detail_Details\' field lists \'Lath & Plaster\'. The Boolean filter was not applied, but the project type and material list suggest moderate relevance."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "EIFS & Stucco Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete",\n      "Water Systems",\n      "Sewerage & Drainage"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project is a multi-residential development with Divisions including Lath & Plaster, Water Systems, Sewerage & Drainage. The project description does not explicitly mention EIFS or Stucco but the presence of lath & plaster and the project type suggest a moderate potential."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "FRP Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "Project is an apartment complex which often uses FRP in kitchens and bathrooms. Project details mention Lath & Plaster, which could be used as a substrate for FRP. Although concrete is present, project seems to be more focused on apartment buildout and thus only moderate priority, Title and scope do not include the product search query."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Fry Reglet Sales",\n    "Product priority": "high",\n    "Materials matching": [\n      "Concrete Formwork",\n      "Concrete Reinforcement",\n      "Structural Concrete",\n      "Lath & Plaster",\n      "Partitions",\n      "Ductwork",\n      "Landscaping"\n    ],\n    "Relevance Classification": "Moderate",\n    "Reasoning": "The project is an apartment complex, which could use Fry Reglet products.  It is listed as having \'Lath & Plaster\' in the details, which are highly relevant materials.  The size and value of the project are substantial, but the lack of direct mentions of the product category limits the classification."\n  }\n]\n',
 '\n[\n  {\n    "ProjectID": 1006879795,\n    "Product": "Georgia Pacific Drywall Sales",\n    "Product priority": "low",\n    "Materials matching": [\n      "Lath & Plaster",\n      "Gypsum Board",\n      "Insulation",\n      "Acoustical Ceilings"\n    ],\n    "Relevance Classification": "moderate",\n    "Reasoning": "The project is an apartment complex with concrete, metal, and wood framing. The materials match insulation, Lath & Plaster, Acoustical Ceilings and Gypsum Board are relevant.  The project details mention Lath & Plaster specifically, and the project type aligns with potential drywall usage, but the low product priority limits the classification."\n  }\n]\n',

In [129]:
all_data = []
for item in product_responses:
    try:
        # Load each string as JSON, handling potential errors
        json_list = json.loads(item)
        all_data.extend(json_list)  # Extend the list with the parsed dictionaries
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        print(f"Problematic string: {item}")
        continue # Skip to the next string if there's an error


df_single_prompt_output = pd.DataFrame(all_data)

In [130]:
df_single_prompt_output.to_csv('data/single_prompt_output.csv', index=False)

Multiple prompts

In [131]:
def run_prompt_boolean_filter(product, search_query, cc_project_json, product_priority):
    question = f''' 
    **Objective:** Identify if the ConstructConnect project is related to the given product.

    **Instructions:**
        1. **Analyze the provided JSON data** representing ConstructConnect project to understand relevant fields and data.
        2. **Utilize the Boolean filters** corresponding to the **Product Category** to identify if the project is related to the given product by matching across multpile project fields.
        3. **Respond as YES or NO with a reason for your answer in a valid JSON as provided in the Example Output below. RETURN ONLY THE JSON RESPONSE.**

    **JSON Project Data:** 
    {cc_project_json}

    **Product Category:**
    {product}
   
    **Boolean Filters:**
    {search_query}

    **Example Output:**
    [
    {{"ProjectID": 1006193703, "Product": {product}, "Product priority":{product_priority}, "Project related to Product": YES, "Product Reasoning": reason for relation response}},
    ]

    '''

    prompt = question
    contents = [prompt]

    # Generate text using non-streaming method
    response = model.generate_content(contents)
    return response.text

In [132]:
def run_prompt_material_filter(materials, cc_project_json):
    question = f''' 
    **Objective:** Identify if the ConstructConnect project has any of the given relevant materials.

    **Instructions:**
        1. **Analyze the provided JSON data** representing ConstructConnect project to understand relevant fields and data.
        2. **Utilize the Materials list** to identify if the project has any of the materials listed by matching across multpile project fields.
        3. **Respond as YES or NO with a list of all the materials mentioned in your answer in a valid JSON as provided in the Example Output below. RETURN ONLY THE JSON RESPONSE.**

    **JSON Project Data:** 
    {cc_project_json}

    **Materials List:**
    {materials}
   

    **Example Output:**
    {{"ProjectID": 1006193703, "Relevant materials present": YES, "Materials": ["Material1","Material2", ...], "Reasoning": reason for relation response}},
    '''

    prompt = question
    contents = [prompt]

    # Generate text using non-streaming method
    response = model.generate_content(contents)
    return response.text

In [133]:
def run_prompt_relevance (cc_project_json, materials):
    question = f''' 
    **Objective:** Classify ConstructConnect projects as very high, high, moderate, low, very low and not relevant.

    **Instructions:**
        1. **Analyze the provided JSON data** representing ConstructConnect project, the product it is related to, materials used and the valuation.
        2. **Utilize the Relevant Materials list** provided. THis list contains materials that are very important for the company.
        3. **Utilize the Product Priority** to weight the classifying attributes accordingly.
        4. **Estimate the relevance of the project using the specifed product** based on the materials and the total dollar amount. 
        5. **Respond with a list of project evaluations** in valid JSON as provided in the Example Output below. Classify the projects as very high, high, moderate, low, very low and not relevant. RETURN ONLY THE JSON RESPONSE.

    **JSON Project Data:** 
    {cc_project_json}

    **Materials List:**
    {materials}
   
    **Product Priority:**
    {cc_project_json['Product priority']}

    **Example Output:**
    {{"ProjectID": 1006193703, "Relevance classification": , "Reasoning": reason for classification}}
    '''

    prompt = question
    contents = [prompt]

    # Generate text using non-streaming method
    response = model.generate_content(contents)
    return response.text

In [134]:
def run_separate_prompts(cc_projects_json_records, product_filter_json, materials):
    material_response = run_prompt_material_filter(materials, cc_projects_json_records)
    material_response_json = json.loads(material_response.replace("```json", "").replace("```", ""))
   
    product_responses = []
    for item in product_filter_json:
        output = run_prompt_boolean_filter(item['Filter'], item['Query'], cc_projects_json_records, item['Priority'])
        product_responses.append(output.replace("```json", "").replace("```", "").replace("[", "").replace("]", ""))
    return product_responses, material_response_json,

In [135]:
def create_dataframe(json_strings, material_data):
    """Creates a Pandas DataFrame from JSON strings and adds material data."""
    data = []
    for json_str in json_strings:
        try:
            cleaned_json_str = json_str.strip()
            if cleaned_json_str:
              json_data = json.loads(cleaned_json_str)
              data.append(json_data)
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")
            print(f"Problematic string: {json_str}")
            return None
        except Exception as e:
            print(f"An error occurred: {e}")
            return None

    if not data:
      return None

    df = pd.DataFrame(data)

    # Add the material columns.  This is the key change:
    df["Relevant materials present"] = material_data["Relevant materials present"]
    df["Materials"] = [material_data["Materials"]] * len(df) # Important: Make it a list of lists
    df["Materials Reasoning"] = [material_data["Reasoning"]] * len(df) # Important: Make it a list of lists


    return df

In [136]:
parameters_df = pd.DataFrame()
for index, row in cc_data_subset.iterrows():  # Iterate through rows
    row_json_str = row.to_json()  # Convert row to dictionary
    cc_project_json_record = json.loads(row_json_str) 
    print(cc_project_json_record)

    product_responses, material_response = run_separate_prompts(cc_project_json_record, product_filter_json, materials)
    df = create_dataframe(product_responses, material_response)
    df["Valuation"] = [cc_project_json_record["Valuation_Value"]]*len(df)
    parameters_df = pd.concat([parameters_df, df], ignore_index=True)

{'ProjectID': 1006872527, 'DataSourceID': 'US', 'Title': 'Agawam Police Department Addition/Renovation', 'Stage': 'Low Bids Announced', 'URL': 'http://insight.cmdgroup.com/SingleSignOn/ProjectDetails/1006872527/1/', 'UpdateDate': '2023-08-28', 'IsProspective': False, 'UpdateText': 'Project reviewed, Stage confirmed as Low Bids Announced', 'Valuation_Value': 4637163.0, 'Valuation_Currency': 'USD', 'Valuation_ValueType': 'Confirmed Value', 'Parameters_Parameter_Ownership': 'City', 'Parameters_Parameter_WorkType': 'Addition/Alteration', 'Parameters_Parameter_CommenceDate': '2023-10-20', 'Parameters_Parameter_FloorArea': 18000.0, 'Parameters_Parameter_Structures': 2.0, 'Parameters_Parameter_Units': None, 'Parameters_Parameter_BidDate': '2023-08-22', 'Parameters_Parameter_FloorAreaUnitofMeasure': 'Square Feet', 'Parameters_Parameter_IsSingleTrade': False, 'DocumentAvailability_Plans': True, 'DocumentAvailability_Specs': True, 'DocumentAvailability_Addenda': True, 'ParentCategories_PrimaryCategoryName': 'Fire and Police Stations', 'ParentCategories_ParentCategory': [{'_Name': None, 'ns0:SubCategories': {'ns0:SubCategory': ['Fire and Police Stations']}}], 'Addresses_Address': [{'_ProjectAddressType': None, 'ns0:AddressLine1': '681 Springfield St', 'ns0:AddressLine2': None, 'ns0:City': 'Agawam', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:Latitude': 42.072375, 'ns0:Longitude': -72.675163, 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01030'}], 'Contracts_Contract': [{'_BidDate': None, '_BidTime': None, '_BidType': None, '_BidsTo': None, '_Bonding': None, '_Classification': None, '_Invitation': None, '_PlansFrom': None}], 'ProjectEvents_ProjectEvent': [{'ns0:Event': 'Plans Available', 'ns0:EventDate': '2023-07-26', 'ns0:EventDetails': None, 'ns0:EventTime': '09:00AM'}, {'ns0:Event': 'Start Date', 'ns0:EventDate': '2023-10-20', 'ns0:EventDetails': 'Actual Start Date', 'ns0:EventTime': None}, {'ns0:Event': 'Bid Date', 'ns0:EventDate': '2023-08-22', 'ns0:EventDetails': 'Bids received by Town Hall Town of Agawam 36 Main St Agawam MA US, 01001', 'ns0:EventTime': '02:00PM'}], 'Companies': [{'ns0:Company': [{'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '521 East St.', 'ns0:AddressLine2': None, 'ns0:City': 'Chicopee', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01020'}]}, 'ns0:BidderRoles': None, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'jhanifan@cbaarchitects.net', 'ns0:LinkedInURL': 'http://www.linkedin.com/pub/jim-hanifan/2a/a92/84a', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'cedgin@CBAarchitects.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jhanifan@cbaarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/jim-hanifan-84aa922a', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'bgardner@cbaarchitects.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'edemers@cbaarchitects.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jmacmillan@cbaarchitects.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@CBAarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/craig-spice-46ab9310/', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@CBAarchitects.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@cbaarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/elizabeth-taylor-50776615a/', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'rhall@cbaarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/rudolph-hall-465a56a2/', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jfiore@CBAarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/jwfiore/', 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@cbaarchitects.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135942800'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'rhall@cbaarchitects.net', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/rudolph-hall-465a56a2/', 'ns0:PhoneNumber': '4135942800'}]}, 'ns0:Email': 'info@cbaarchitects.net', 'ns0:ParticipantRoles': {'ns0:ParticipantRole': {'_ContactId': None, '_ContactName': None, '_RoleClassification': None, '_RoleStatus': None}}, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://cbaarchitects.net/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '36 Main St', 'ns0:AddressLine2': None, 'ns0:City': 'Agawam', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01001'}]}, 'ns0:BidderRoles': None, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': None}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4138210506'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': None}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': None}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'wreichelt@agawam.ma.us', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'rkupec@agawam.ma.us', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': None}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'Malbro@agawam.ma.us', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/michael-albro-a5186a79/', 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jbonfiglio@agawam.ma.us', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/jennifer-bonfiglio-aaaa34a4/', 'ns0:PhoneNumber': '4137269742'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'mstrange@agawam.ma.us', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/attorneystrange', 'ns0:PhoneNumber': '4137269738'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'akeeney@agawam.ma.us', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': 'http://www.linkedin.com/pub/christopher-golba/52/73/a09', 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'shekarco@verizon.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'mchase@agawam.ma.us', 'ns0:LinkedInURL': 'http://www.linkedin.com/in/mcchase', 'ns0:PhoneNumber': '4138210625'}, {'_ContactID': None, '_Name': None, 'ns0:Email': None, 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137860400'}]}, 'ns0:Email': None, 'ns0:ParticipantRoles': {'ns0:ParticipantRole': {'_ContactId': None, '_ContactName': None, '_RoleClassification': None, '_RoleStatus': None}}, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://www.agawam.ma.us/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '18 Graf Road', 'ns0:AddressLine2': None, 'ns0:City': 'Newburyport', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Essex', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01950'}]}, 'ns0:BidderRoles': None, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'addenda@projectdog.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/eric-carpenter-1b764712/', 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'frontdesk@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'addenda@proiectdog.com', 'ns0:LinkedInURL': 'http://www.linkedin.com/pub/joshua-berry/28/629/11', 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'mike.carter@gcgassociates.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': None}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'addenda@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'davidc@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'addenda@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'frontdesk@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'frontdesk@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'BidCoordinator@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'BidCoordinator33@projectdog.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '9784999014'}]}, 'ns0:Email': 'addenda@projectdog.com', 'ns0:ParticipantRoles': {'ns0:ParticipantRole': {'_ContactId': None, '_ContactName': None, '_RoleClassification': None, '_RoleStatus': None}}, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://www.projectdog.com/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '165 Trilby Avenue', 'ns0:AddressLine2': None, 'ns0:City': 'Chicopee', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01020'}]}, 'ns0:BidderRoles': {'ns0:Bidder': [{'_BidCreateDate': None, '_BidRank': None, '_BidValue': None, '_BidWithdrawDate': None, '_BidderClassification': None}]}, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}, {'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'davidking@ayotteandking.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/david-king-89a1a12b/', 'ns0:PhoneNumber': '4135329463'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'Info@ayotteandking.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135329463'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@ayotteandking.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135329463'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'cindyking@ayotteandking.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135329463'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'cindyking@ayotteandking.Ccoymnthia', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135329463'}]}, 'ns0:Email': 'info@ayotteandking.com', 'ns0:ParticipantRoles': None, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://www.ayotteandking.com/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '371 Taylor Street', 'ns0:AddressLine2': 'P.O. Box 2070', 'ns0:City': 'Springfield', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01101'}]}, 'ns0:BidderRoles': {'ns0:Bidder': [{'_BidCreateDate': None, '_BidRank': None, '_BidValue': None, '_BidWithdrawDate': None, '_BidderClassification': None}]}, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'marcp@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'kyleb@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/kyle-bousquet-7789ab10a/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/thomas-schmitt-2ab92446/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/cheryl-lafleur-59311a10a', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'CathyS@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'petec@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/peter-coppez-56a92456/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'nateq@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'tuckers@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/tucker-schmitt-07790311/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/thomas-schmitt-2ab92446/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'daveb@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135377036'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'kyleb@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/kyle-bousquet-7789ab10a/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jeffd@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4133483992'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jeanc@mlschmittelectric.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/jean-pierre-crevier-263a7b21/', 'ns0:PhoneNumber': '4137337868'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137337868'}]}, 'ns0:Email': 'info@mlschmittelectric.com', 'ns0:ParticipantRoles': None, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://www.mlschmittelectric.com/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '43 Printworks Drive,', 'ns0:AddressLine2': 'P.O. Box 126', 'ns0:City': 'Adams', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Berkshire', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01220'}]}, 'ns0:BidderRoles': {'ns0:Bidder': [{'_BidCreateDate': None, '_BidRank': None, '_BidValue': None, '_BidWithdrawDate': None, '_BidderClassification': None}]}, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}, {'_Rank': None, '_Type': None}, {'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'jbenlien@adamsphinc.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/jim-benlien-87756592/', 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'a.moresi@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'k.daignault@adamsphinc.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/kurt-daignault-70249524/', 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'adamsph@osage.net', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '6417325623'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'w.daignault@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'j.daignault@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'info@adamsphinc.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4137432308'}]}, 'ns0:Email': 'info@adamsphinc.com', 'ns0:ParticipantRoles': None, 'ns0:Phones': {'ns0:Phone': [{'_': None, '_PhoneType': None}, {'_': None, '_PhoneType': None}]}, 'ns0:Website': 'http://www.adamsphinc.com/'}, {'_BiddingRole': None, '_CompanyID': None, '_DataSourceID': None, '_LastUpdate': None, '_Name': None, '_Role': None, '_URL': None, 'ns0:Addresses': {'ns0:Address': [{'_AddressType': None, 'ns0:AddressLine1': '53 Second Ave.', 'ns0:AddressLine2': None, 'ns0:City': 'Chicopee', 'ns0:CountryRegion': 'UNITED STATES', 'ns0:County': 'Hampden', 'ns0:StateProvince': 'MA', 'ns0:ZipPostalCode': '01020'}]}, 'ns0:BidderRoles': None, 'ns0:ClassificationTypes': {'ns0:ClassificationType': [{'_Rank': None, '_Type': None}]}, 'ns0:Contacts': {'ns0:Contact': [{'_ContactID': None, '_Name': None, 'ns0:Email': 'mdecelle@collinselectricco.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135981022'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'janderson@collinselectricco.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/john-anderson-23228868/', 'ns0:PhoneNumber': '4154495060'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'cdonahue@collinselectricco.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/chris-donahue-donahue-1a545a3a/', 'ns0:PhoneNumber': '4135481000'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'fgingras@collinselectricco.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/frank-gingras-68aba12a/', 'ns0:PhoneNumber': '4134495061'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'dhelsel@collinselectric.com', 'ns0:LinkedInURL': None, 'ns0:PhoneNumber': '4135929221'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'boconnor@collinselectricco.com', 'ns0:LinkedInURL': 'https://www.linkedin.com/in/brian-oconnor-6393963a/', 'ns0:PhoneNumber': '4135929221'}, {'_ContactID': None, '_Name': None, 'ns0:Email': 'jmahan@collinselectricco.c

In [137]:
parameters_df

,ProjectID,Product,Product priority,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation
0,1006872527,3M Sales,low,NO,The provided data does not contain any direct ...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
1,1006872527,Access Door Sales,low,NO,The provided project data does not contain any...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
2,1006872527,Ceiling Sales,high,YES,"The Details_Detail_Scope mentions ""CEILINGS:Ro...",YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
3,1006872527,Certainteed Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
4,1006872527,Cultured Stone Sales,low,YES,The project details mention 'Stone' and 'Stone...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
5,1006872527,Drywall Sales,high,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
6,1006872527,EIFS & Stucco Sales,high,YES,The project scope mentions 'Exterior Insulatio...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
7,1006872527,FRP Sales,high,YES,The Details_Detail_Scope field mentions 'FLOOR...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
8,1006872527,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
9,1006872527,Georgia Pacific Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' i...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
10,1006872527,Insulation Sales,high,YES,The project scope mentions 'Insulation' under ...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
11,1006872527,Nichiha Sales,high,NO,The provided JSON data does not contain any in...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
12,1006872527,Pabco Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
13,1006872527,Steel Sales,high,YES,The project details mention 'Structural Steel'...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0
14,1006879795,3M Sales,low,NO,The project data does not contain any explicit...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
15,1006879795,Access Door Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
16,1006879795,Ceiling Sales,high,YES,The project details mention 'Lath & Plaster' i...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
17,1006879795,Certainteed Drywall Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
18,1006879795,Cultured Stone Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
19,1006879795,Drywall Sales,high,YES,"The project details include 'Lath & Plaster', ...",YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
20,1006879795,EIFS & Stucco Sales,high,YES,The 'Details_Detail_Details' field includes 'L...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
21,1006879795,FRP Sales,high,NO,The provided JSON data does not contain any ke...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
22,1006879795,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
23,1006879795,Georgia Pacific Drywall Sales,low,YES,The project details mention 'Lath & Plaster' a...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
24,1006879795,Insulation Sales,high,YES,"The Details_Detail_Details field includes ""The...",YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
25,1006879795,Nichiha Sales,high,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
26,1006879795,Pabco Drywall Sales,low,YES,The project details mention 'Lath & Plaster' a...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
27,1006879795,Steel Sales,high,YES,The project details mention 'Concrete Reinforc...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0
28,1006891936,3M Sales,low,NO,The project data does not contain any keywords...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
29,1006891936,Access Door Sales,low,NO,The project is a courthouse renovation involvi...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
30,1006891936,Ceiling Sales,high,YES,The project details mention 'new roofing over'...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
31,1006891936,Certainteed Drywall Sales,low,YES,The project involves 'renovation of an existin...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
32,1006891936,Cultured Stone Sales,low,YES,The project details mention 'exterior masonry ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
33,1006891936,Drywall Sales,high,NO,The project description and details primarily ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
34,1006891936,EIFS & Stucco Sales,high,YES,The project details mention 'exterior masonry ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
35,1006891936,FRP Sales,high,NO,The provided project data does not contain any...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
36,1006891936,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
37,1006891936,Georgia Pacific Drywall Sales,low,NO,The project is a courthouse renovation involvi...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
38,1006891936,Insulation Sales,high,YES,"The project scope mentions HVAC work, includin...",YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
39,1006891936,Nichiha Sales,high,NO,The project details do not contain any mention...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
40,1006891936,Pabco Drywall Sales,low,NO,The project data does not contain any informat...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0
41,1006891936,Steel Sales,high,YES,The project details mention 'Miscellaneous & O...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0

In [138]:
parameters_df.to_csv('data/first_pass_output.csv', index=False)

In [139]:
import pandas as pd
import json

def classify_relevance(df):
  
    df["Relevance Classification"] = ""  # Initialize the new column

    for index, row in df.iterrows():
        if row["Project related to Product"] == "NO" or row["Relevant materials present"] == "NO":
            df.loc[index, "Relevance Classification"] = "not relevant"
            df.loc[index, "Classification Reasoning"] = 'Project is not related to the product or relevant materials are not present'
        else:
            product_data = {
                "ProjectID": row["ProjectID"],
                "Product": row["Product"],
                "Product priority": row["Product priority"],
                "Materials": row["Materials"],
                "Valuation": row["Valuation"]
            }
            #json_data = json.loads(product_data)

            relevance_classification = run_prompt_relevance(product_data, materials)
            relevance_classification_json = json.loads(relevance_classification.replace("```json", "").replace("```", "").replace("[", "").replace("]", ""))
            df.loc[index, "Relevance Classification"] = relevance_classification_json['Relevance classification']
            df.loc[index, "Classification Reasoning"] = relevance_classification_json['Reasoning']

    return df

In [140]:
classifications_df = classify_relevance(parameters_df)
classifications_df

,ProjectID,Product,Product priority,Project related to Product,Product Reasoning,Relevant materials present,Materials,Materials Reasoning,Valuation,Relevance Classification,Classification Reasoning
0,1006872527,3M Sales,low,NO,The provided data does not contain any direct ...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,not relevant,Project is not related to the product or relev...
1,1006872527,Access Door Sales,low,NO,The provided project data does not contain any...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,not relevant,Project is not related to the product or relev...
2,1006872527,Ceiling Sales,high,YES,"The Details_Detail_Scope mentions ""CEILINGS:Ro...",YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,very high,The project includes multiple high-priority ma...
3,1006872527,Certainteed Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,moderate,The project includes multiple relevant materia...
4,1006872527,Cultured Stone Sales,low,YES,The project details mention 'Stone' and 'Stone...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,moderate,Project includes multiple relevant materials s...
5,1006872527,Drywall Sales,high,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,very high,"The project includes Drywall/Gypsum, Lath & Pl..."
6,1006872527,EIFS & Stucco Sales,high,YES,The project scope mentions 'Exterior Insulatio...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,high,The project involves several key materials rel...
7,1006872527,FRP Sales,high,YES,The Details_Detail_Scope field mentions 'FLOOR...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,very high,The project includes several high-priority mat...
8,1006872527,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,not relevant,Project is not related to the product or relev...
9,1006872527,Georgia Pacific Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' i...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,moderate,Project includes relevant materials like Acous...
10,1006872527,Insulation Sales,high,YES,The project scope mentions 'Insulation' under ...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,very high,The project includes several high-priority mat...
11,1006872527,Nichiha Sales,high,NO,The provided JSON data does not contain any in...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,not relevant,Project is not related to the product or relev...
12,1006872527,Pabco Drywall Sales,low,YES,The project details mention 'Drywall/Gypsum' u...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,moderate,The project includes several relevant material...
13,1006872527,Steel Sales,high,YES,The project details mention 'Structural Steel'...,YES,"[Waterproofing, Roofing, Acoustical Ceilings, ...",The project details mention the following mate...,4637163.0,very high,The project includes several high-priority mat...
14,1006879795,3M Sales,low,NO,The project data does not contain any explicit...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
15,1006879795,Access Door Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
16,1006879795,Ceiling Sales,high,YES,The project details mention 'Lath & Plaster' i...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,high,The project includes 'Lath & Plaster' and 'Met...
17,1006879795,Certainteed Drywall Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
18,1006879795,Cultured Stone Sales,low,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
19,1006879795,Drywall Sales,high,YES,"The project details include 'Lath & Plaster', ...",YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,high,The project is related to 'Drywall Sales' with...
20,1006879795,EIFS & Stucco Sales,high,YES,The 'Details_Detail_Details' field includes 'L...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,very high,The project is related to 'EIFS & Stucco Sales...
21,1006879795,FRP Sales,high,NO,The provided JSON data does not contain any ke...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
22,1006879795,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
23,1006879795,Georgia Pacific Drywall Sales,low,YES,The project details mention 'Lath & Plaster' a...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,moderate,The project involves 'Lath & Plaster' and 'Met...
24,1006879795,Insulation Sales,high,YES,"The Details_Detail_Details field includes ""The...",YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,high,The project includes 'Lath & Plaster' and 'Met...
25,1006879795,Nichiha Sales,high,NO,The provided project data does not contain any...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,not relevant,Project is not related to the product or relev...
26,1006879795,Pabco Drywall Sales,low,YES,The project details mention 'Lath & Plaster' a...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,moderate,The project includes 'Lath & Plaster' and 'Met...
27,1006879795,Steel Sales,high,YES,The project details mention 'Concrete Reinforc...,YES,"[Lath & Plaster, Metal Doors]",The project details mention 'Lath & Plaster' i...,60000000.0,very high,Project involves 'Steel Sales' with a 'high' p...
28,1006891936,3M Sales,low,NO,The project data does not contain any keywords...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
29,1006891936,Access Door Sales,low,NO,The project is a courthouse renovation involvi...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
30,1006891936,Ceiling Sales,high,YES,The project details mention 'new roofing over'...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,The project includes 'Masonry' and 'Roofing' m...
31,1006891936,Certainteed Drywall Sales,low,YES,The project involves 'renovation of an existin...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,low,"Although the project valuation is high, the pr..."
32,1006891936,Cultured Stone Sales,low,YES,The project details mention 'exterior masonry ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,low,The project includes 'Masonry' which is a rele...
33,1006891936,Drywall Sales,high,NO,The project description and details primarily ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
34,1006891936,EIFS & Stucco Sales,high,YES,The project details mention 'exterior masonry ...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,low,"The project is related to EIFS & Stucco Sales,..."
35,1006891936,FRP Sales,high,NO,The provided project data does not contain any...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
36,1006891936,Fry Reglet Sales,high,NO,The provided project data does not contain any...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
37,1006891936,Georgia Pacific Drywall Sales,low,NO,The project is a courthouse renovation involvi...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
38,1006891936,Insulation Sales,high,YES,"The project scope mentions HVAC work, includin...",YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,low,Although the project involves 'Insulation Sale...
39,1006891936,Nichiha Sales,high,NO,The project details do not contain any mention...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
40,1006891936,Pabco Drywall Sales,low,NO,The project data does not contain any informat...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,Project is not related to the product or relev...
41,1006891936,Steel Sales,high,YES,The project details mention 'Miscellaneous & O...,YES,"[Masonry, Roofing]",The 'Details_Detail_Scope' field mentions 'ext...,4093126.0,not relevant,"The project's materials (Masonry, Roofing) are..."

In [141]:
classifications_df.to_csv('data/second_pass_output.csv', index=False)